# Generated by Django 3.1.12 on 2021-08-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_video_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videofile",
            name="destination_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
