# Generated by Django 3.1.12 on 2021-09-10 06:04

import django.db.models.deletion
from django.db import migrations, models

import videos.models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0034_website_title_index"),
        ("videos", "0003_videofile_destination_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="pdf_transcript_file",
            field=models.FileField(
                blank=True,
                max_length=2048,
                null=True,
                upload_to=videos.models.Video.upload_file_to,
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="webvtt_transcript_file",
            field=models.FileField(
                blank=True,
                max_length=2048,
                null=True,
                upload_to=videos.models.Video.upload_file_to,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="websites.website",
            ),
        ),
    ]
