# Generated by Django 3.1.14 on 2022-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_video_transcript_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="job_output",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
