# Generated by Django 3.1 on 2020-12-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="hugo_filepath",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
