# Generated by Django 3.1 on 2021-02-02 18:02

import django.db.models.deletion
from django.db import migrations, models

import websites.models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0002_websitecontent_hugo_filepath"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteStarter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        help_text="Github repo path or local file path of the starter project.",  # noqa: E501
                        max_length=256,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-friendly name of the starter project.",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("github", "github"), ("local", "local")],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "commit",
                    models.CharField(
                        blank=True,
                        help_text="Commit hash for the repo (if this commit came from a Github starter repo).",  # noqa: E501
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.TextField(
                        help_text="YML-formatted site config.",
                        validators=[websites.models.validate_yaml],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="website",
            name="starter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="websites.websitestarter",
            ),
        ),
    ]
