# Generated by Django 3.1 on 2021-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0008_site_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitecontent",
            name="type",
            field=models.CharField(
                choices=[("page", "page"), ("file", "file")],
                default="page",
                max_length=24,
            ),
            preserve_default=False,
        ),
    ]
