# Generated by Django 3.1 on 2021-02-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0010_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("studio", "studio"), ("ocw-import", "ocw-import")],
                default="studio",
                max_length=20,
                null=True,
            ),
        ),
    ]
