# Generated by Django 3.1 on 2021-02-25 22:35

from django.db import migrations, models


def set_website_title(apps, schema_editor):
    Website = apps.get_model("websites", "Website")
    no_title_websites = Website.objects.filter(title=None).all()
    for website in no_title_websites:
        website.title = f"Website ({website.name})"
        website.save()


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0011_default_website_source"),
    ]

    operations = [
        migrations.RunPython(set_website_title, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="website",
            name="title",
            field=models.CharField(max_length=512),
        ),
    ]
