# Generated by Django 3.1 on 2021-02-25 22:35

from django.db import migrations, models


def _update_description_widget(starter, new_widget):
    collections = starter.config["collections"]
    changed = False
    for item in collections:
        if item["name"] == "resource":
            for field in item["fields"]:
                if field["name"] == "description":
                    field["widget"] = new_widget
                    changed = True
    if changed:
        starter.config = {"collections": collections}
        starter.save()


def update_description_widget(apps, schema_editor):
    WebsiteStarter = apps.get_model("websites", "WebsiteStarter")

    starter = WebsiteStarter.objects.filter(slug="course").first()
    if starter:
        _update_description_widget(starter, "text")
        starter.save()


def revert_description_widget(apps, schema_editor):
    WebsiteStarter = apps.get_model("websites", "WebsiteStarter")

    starter = WebsiteStarter.objects.filter(slug="course").first()
    if starter:
        _update_description_widget(starter, "markdown")
        starter.save()


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0012_website_title_required"),
    ]

    operations = [
        migrations.RunPython(update_description_widget, revert_description_widget),
    ]
