# Generated by Django 3.1 on 2021-02-25 22:35

from django.db import migrations, models


def _update_widget(starter, old_widget, new_widget):
    collections = starter.config["collections"]
    for item in collections:
        for field in item["fields"]:
            if field["name"] == "description" and field["widget"] == old_widget:
                field["widget"] = new_widget
    if collections != starter.config["collections"]:
        starter.config = {"collections": collections}
        starter.save()


def update_description_widget(apps, schema_editor):
    WebsiteStarter = apps.get_model("websites", "WebsiteStarter")

    for starter in WebsiteStarter.objects.all():
        _update_widget(starter, "markdown", "string")


def revert_description_widget(apps, schema_editor):
    WebsiteStarter = apps.get_model("websites", "WebsiteStarter")

    for starter in WebsiteStarter.objects.all():
        _update_widget(starter, "string", "markdown")


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0012_website_title_required"),
    ]

    operations = [
        migrations.RunPython(update_description_widget, revert_description_widget),
    ]
