# Generated by Django 3.1 on 2021-03-04 15:28

from django.db import migrations, models

import websites.models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0013_description_as_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                max_length=2048,
                upload_to=websites.models.WebsiteContent.upload_file_to,
            ),
        ),
    ]
