# Generated by Django 3.1.6 on 2021-04-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0016_remove_site_content_type_constraint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="websitecontent",
            old_name="hugo_filepath",
            new_name="content_filepath",
        ),
    ]
