# Generated by Django 3.1.6 on 2021-04-15 01:41

from uuid import UUID, uuid4

from django.db import migrations, models
from django.db.models.functions import Length

import main.utils


def change_text_id_to_uuid(apps, schema_editor):
    """
    Fetches all WebsiteContent records with a non-uuid text_id value, and generates a uuid for them. This is to
    prepare those records for reversing this migration
    """
    WebsiteContent = apps.get_model("websites", "WebsiteContent")
    possible_non_uuid_qset = WebsiteContent.objects.annotate(
        text_id_len=Length("text_id")
    ).exclude(text_id_len=36)
    for website_content in possible_non_uuid_qset:
        try:
            UUID(str(website_content.text_id), version=4)
        except ValueError:
            website_content.text_id = uuid4()
            website_content.save()


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0018_rename_uuid_to_text_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitecontent",
            name="text_id",
            field=models.CharField(
                db_index=True, default=main.utils.uuid_string, max_length=36
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, change_text_id_to_uuid),
    ]
