# Generated by Django 3.1.6 on 2021-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0020_websitecontent_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="is_page_content",
            field=models.BooleanField(
                default=False,
                help_text="If True, indicates that this content represents a navigable page, as opposed to some metadata, configuration, etc.",
            ),
        ),
    ]
