# Generated by Django 3.1.6 on 2021-05-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0023_website_content_filepath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitecontent",
            name="filename",
            field=models.CharField(default="", max_length=125),
        ),
        migrations.AlterUniqueTogether(
            name="websitecontent",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="websitecontent",
            constraint=models.UniqueConstraint(
                fields=("website", "text_id"), name="unique_text_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="websitecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, dirpath=None),
                fields=("website", "type", "dirpath", "filename"),
                name="unique_destination_filepath",
            ),
        ),
        migrations.AddConstraint(
            model_name="websitecontent",
            constraint=models.UniqueConstraint(
                condition=models.Q(dirpath=None),
                fields=("website", "type", "filename"),
                name="unique_destination_filepath_null_dir",
            ),
        ),
    ]
