# Generated by Django 3.1.6 on 2021-05-14 14:55
import json
from hashlib import sha256

from django.db import migrations


def calculate_checksum(website_content):
    """Returns a calculated checksum of the content"""  # noqa: D401
    return sha256(
        "\n".join(
            [
                json.dumps(website_content.metadata, sort_keys=True),
                str(website_content.title),
                str(website_content.markdown),
                website_content.type,
                str(website_content.dirpath),
                str(website_content.filename),
            ]
        ).encode("utf-8")
    ).hexdigest()


def recalculate_checksums(apps, schema_editor):
    """
    Updates checksum values for all ContentSyncState objects due to a change in the checksum properties
    """  # noqa: E501, D401
    ContentSyncState = apps.get_model("content_sync", "ContentSyncState")
    sync_states = ContentSyncState.objects.select_related("content").all()
    for sync_state in sync_states:
        sync_state.current_checksum = calculate_checksum(sync_state.content)
        sync_state.save()


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0024_content_unique_destination_filepath"),
    ]

    operations = [
        migrations.RunPython(recalculate_checksums, migrations.RunPython.noop),
    ]
