# Generated by Django 3.1.8 on 2021-06-15 13:02

from django.db import migrations, models

import websites.models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0026_remove_content_filepath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitestarter",
            name="slug",
            field=models.CharField(
                help_text="Short string that can be used to identify this starter.",
                max_length=30,
                validators=[websites.models.validate_slug],
            ),
        ),
        migrations.AddConstraint(
            model_name="websitestarter",
            constraint=models.UniqueConstraint(
                fields=("path", "slug"), name="unique_repo_slug"
            ),
        ),
    ]
