# Generated by Django 3.1.12 on 2021-06-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0028_omnibus_site_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="file_fieldname",
            field=models.CharField(default="file", max_length=256),
        ),
    ]
