# Generated by Django 3.1.6 on 2021-06-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0029_websitecollection_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitecontent",
            name="dirpath",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The directory path for the file that will be created from this object.",  # noqa: E501
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="filename",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The filename of the file that will be created from this object WITHOUT the file extension.",  # noqa: E501
                max_length=125,
            ),
        ),
    ]
