# Generated by Django 3.1.12 on 2021-07-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0031_website_short_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="short_id",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
