# Generated by Django 3.1.12 on 2021-07-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0032_website_short_id_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websitecontent",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True
            ),
        ),
    ]
