# Generated by Django 3.1.12 on 2021-07-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0033_websitecontent_title_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="title",
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
