# Generated by Django 3.1.12 on 2021-10-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0034_website_title_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="draft_publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="has_unpublished_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="website",
            name="has_unpublished_live",
            field=models.BooleanField(default=True),
        ),
    ]
