# Generated by Django 3.1.13 on 2021-10-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0036_fix_sitemetadata_textid"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="gdrive_folder",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
