# Generated by Django 3.1.13 on 2021-10-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0037_website_gdrive_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="draft_publish_status",
            field=models.CharField(
                choices=[
                    ("succeeded", "succeeded"),
                    ("pending", "pending"),
                    ("errored", "errored"),
                    ("aborted", "aborted"),
                    ("not-started", "not-started"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="draft_publish_status_updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="live_publish_status",
            field=models.CharField(
                choices=[
                    ("succeeded", "succeeded"),
                    ("pending", "pending"),
                    ("errored", "errored"),
                    ("aborted", "aborted"),
                    ("not-started", "not-started"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="live_publish_status_updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
