# Generated by Django 3.1.13 on 2021-10-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0038_website_publish_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="sync_errors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="sync_status",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="synced_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
