# Generated by Django 3.1.13 on 2021-11-04 18:10

from django.db import migrations

from websites.constants import WEBSITE_SOURCE_STUDIO
from websites.models import WebsiteContent


def add_ten_to_weights(apps, schema_editor):
    navmenus = WebsiteContent.objects.filter(
        type="navmenu", website__source=WEBSITE_SOURCE_STUDIO
    )
    for navmenu in navmenus:
        for menuitem in navmenu.metadata["leftnav"]:
            menuitem["weight"] += 10
        navmenu.save()


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0039_gdrive_sync_progress"),
    ]

    operations = [migrations.RunPython(add_ten_to_weights)]
