# Generated by Django 3.1.13 on 2021-11-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0040_no_zero_menu_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="latest_build_id_draft",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="latest_build_id_live",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="website",
            name="draft_publish_status",
            field=models.CharField(
                choices=[
                    ("succeeded", "succeeded"),
                    ("pending", "pending"),
                    ("started", "started"),
                    ("errored", "errored"),
                    ("aborted", "aborted"),
                    ("not-started", "not-started"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="live_publish_status",
            field=models.CharField(
                choices=[
                    ("succeeded", "succeeded"),
                    ("pending", "pending"),
                    ("started", "started"),
                    ("errored", "errored"),
                    ("aborted", "aborted"),
                    ("not-started", "not-started"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
