# Generated by Django 3.1.14 on 2022-01-05 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0042_last_published_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websitecollectionitem",
            name="website",
        ),
        migrations.RemoveField(
            model_name="websitecollectionitem",
            name="website_collection",
        ),
        migrations.DeleteModel(
            name="WebsiteCollection",
        ),
        migrations.DeleteModel(
            name="WebsiteCollectionItem",
        ),
    ]
