# Generated by Django 3.1.14 on 2022-04-22 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("websites", "0045_blank_publish_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="last_unpublished_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unpublisher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="unpublish_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("succeeded", "succeeded"),
                    ("pending", "pending"),
                    ("started", "started"),
                    ("errored", "errored"),
                    ("aborted", "aborted"),
                    ("not-started", "not-started"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="website",
            name="unpublish_status_updated_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
