# Generated by Django 3.1.14 on 2022-05-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0047_unpublish_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="url_path",
            field=models.CharField(max_length=2048, null=True, unique=True),
        ),
    ]
