# Generated by Django 3.1.14 on 2022-05-12 18:40
from urllib.parse import urljoin

from django.conf import settings
from django.db import migrations, models, transaction

from websites.constants import CONTENT_TYPE_METADATA
from websites.site_config_api import SiteConfig
from websites.utils import set_dict_field


def populate_url_path(apps, schema_editor):
    """
    Populate url_path for all sites that have been published to production
    """
    Website = apps.get_model("websites", "Website")
    for site in Website.objects.exclude(first_published_to_production__isnull=True):
        if site.starter is None:
            continue
        with transaction.atomic():
            site_config = SiteConfig(site.starter.config)
            root = site_config.root_url_path
            site.url_path = urljoin(root, site.name)
            site.save()
            content = site.websitecontent_set.filter(type=CONTENT_TYPE_METADATA).first()
            if content:
                set_dict_field(
                    content.metadata, settings.FIELD_METADATA_S3_PATH, site.url_path
                )
                set_dict_field(
                    content.metadata, settings.FIELD_METADATA_URL_PATH, site.url_path
                )
                content.save()


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0047_unpublish_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="url_path",
            field=models.CharField(max_length=2048, null=True, blank=True, unique=True),
        ),
        migrations.RunPython(populate_url_path, migrations.RunPython.noop),
    ]
