# Generated by Django 3.1.14 on 2022-05-10 13:49
from django.db import migrations

from websites.constants import WEBSITE_SOURCE_STUDIO


def migrate_fields_forward(apps, schema_editor):
    migrate_field(apps, True)  # noqa: FBT003


def migrate_fields_backward(apps, schema_editor):
    migrate_field(apps, False)  # noqa: FBT003


def migrate_field(apps, forward):
    WebsiteStarter = apps.get_model("websites", "WebsiteStarter")
    Website = apps.get_model("websites", "Website")
    WebsiteContent = apps.get_model("websites", "WebsiteContent")
    original_type = "pages" if forward else "page"
    updated_type = "page" if forward else "pages"
    try:
        www_starter = WebsiteStarter.objects.get(name="ocw-www")
        ocw_www_sites = Website.objects.filter(starter=www_starter)
        for ocw_www in ocw_www_sites:
            resources = WebsiteContent.objects.filter(
                type=original_type,
                website=ocw_www,
                website__source=WEBSITE_SOURCE_STUDIO,
            )
            for resource in resources:
                resource.type = updated_type
                resource.save()
    except WebsiteStarter.DoesNotExist:
        return


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0047_unpublish_fields"),
    ]

    operations = []
