# Generated by Django 3.1.14 on 2022-05-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0049_websitestarter_status"),
        ("websites", "0049_website_url_path"),
    ]

    operations = []
