# Generated by Django 3.1.14 on 2022-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0050_modify_course_lists"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitestarter",
            name="status",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                help_text="Starters with only Active and Default status will be shown while creating a new site.",  # noqa: E501
                max_length=30,
            ),
        ),
    ]
