# Generated by Django 3.1.14 on 2022-05-26 15:24

from django.db import migrations


def migrate_fields_forward(apps, schema_editor):
    migrate_field(apps, True)  # noqa: FBT003


def migrate_fields_backward(apps, schema_editor):
    migrate_field(apps, False)  # noqa: FBT003


def migrate_field(apps, forward):
    WebsiteStarter = apps.get_model("websites", "WebsiteStarter")
    WebsiteContent = apps.get_model("websites", "WebsiteContent")
    try:
        course_starter = WebsiteStarter.objects.get(name="ocw-course")
        resource_content = WebsiteContent.objects.filter(
            website__starter=course_starter,
            type="resource",
            metadata__description__isnull=False,
        )
        for content in resource_content:
            if forward:
                content.markdown = (
                    content.metadata["description"]
                    if content.markdown == "" or content.markdown is None
                    else f'{content.markdown}\n\n{content.metadata["description"]}'
                )
                content.metadata["description"] = ""
            else:
                content.metadata["description"] = content.markdown
                content.markdown = ""
            content.save()
    except WebsiteStarter.DoesNotExist:
        return


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0051_websitestarter_status"),
    ]

    operations = [migrations.RunPython(migrate_fields_forward, migrate_fields_backward)]
