# Generated by Django 3.2.19 on 2023-06-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0052_resource_description_to_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitecontent",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="websitecontent",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
