# Generated by Django 3.1.14 on 2022-06-07 22:09
# Migration 0052 had the side effect of duplicating the
# description in some resources. The purpose of this migration
# is to fix that by finding the largest substring in the description
from collections import deque
from django.db import migrations


def largest_substring(string):
    lines = list(string)
    line_deque = deque(string[1:])
    match = []
    longest_match = []
    while line_deque:
        for i, item in enumerate(line_deque):
            if lines[i] == item:
                match.append(item)
            else:
                if len(longest_match) < len(match):
                    longest_match = match
                match = []
        line_deque.popleft()
    return "".join(longest_match)


def migrate_fields_forward(apps, schema_editor):
    migrate_field(apps)


def migrate_fields_backward(apps, schema_editor):
    # Cannot migrate backward
    return


def migrate_field(apps):
    WebsiteStarter = apps.get_model("websites", "WebsiteStarter")
    WebsiteContent = apps.get_model("websites", "WebsiteContent")
    try:
        course_starter = WebsiteStarter.objects.get(name="ocw-course")
        resource_content = WebsiteContent.objects.filter(
            website__starter=course_starter,
            type="resource",
            markdown__isnull=False,
        )
        for content in resource_content:
            content.markdown = largest_substring(content.markdown)
            content.save()
    except WebsiteStarter.DoesNotExist:
        return


class Migration(migrations.Migration):

    dependencies = [
        ("websites", "0052_resource_description_to_body"),
    ]

    operations = [migrations.RunPython(migrate_fields_forward, migrate_fields_backward)]
