# Generated by Django 4.2.15 on 2024-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0056_add_hide_download_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="draft_build_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="live_build_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
