# Generated by Django 4.2.24 on 2025-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0062_remove_course_introduction_lrt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='latest_build_id_draft',
            field=models.IntegerField(blank=True, help_text='Concourse site pipeline build ID for builds triggered through Studio publish. This field is not updated by mass builds or site builds triggered outside of Studio.', null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='latest_build_id_live',
            field=models.IntegerField(blank=True, help_text='Concourse site pipeline build ID for builds triggered through Studio publish. This field is not updated by mass builds or site builds triggered outside of Studio.', null=True),
        ),
    ]
