content-dir: content
root-url-path: "sites"
collections:
  - name: blog
    label: Blog
    category: Content
    folder: content/blog
    fields:
      - {"label": "Title", "name": "title", "widget": "string", "required": true}
  - name: bio
    label: Bio
    category: Content
    folder: content/bio
    fields:
      - {"label": "Title", "name": "title", "widget": "string", "required": true}
  - name: metadata
    label: Metadata
    category: Settings
    files:
      - file: data/metadata.json
        name: sitemetadata
        label: Site Metadata
        fields:
          - {"label": "Title", "name": "title", "widget": "string", "required": true}
  - name: resource
    label: Resource
    category: Content
    folder: content/resource
    fields:
      - {"label": "Title", "name": "title", "widget": "string", "required": true}
      - {"label": "Image", "name": "image", "widget": "file", "required": false}
