---
root-url-path: ""
collections:
  - category: Content
    folder: content/pages
    label: Pages
    name: page
    fields:
      - label: Draft
        name: draft
        required: true
        widget: boolean
        help: Enable this setting to prevent publishing in production

      - label: Title
        name: title
        widget: string
        required: true

      - label: Body
        name: body
        widget: markdown
        minimal: false
        link:
          - course_collections
          - resource_collections
          - resource
          - page
        embed:
          - resource

  - category: Content
    folder: content/resource_collections
    label: "Resource Collections"
    name: "resource_collections"
    fields:
      - label: Draft
        name: draft
        required: true
        widget: boolean
        help: Enable this setting to prevent publishing in production

      - label: Title
        name: title
        widget: string
        required: true

      - label: Description
        name: description
        widget: markdown

      - widget: relation
        name: resources
        label: Resources
        collection: resource
        display_field: title
        cross_site: true
        sortable: true

  - category: Content
    folder: content/course-lists
    label: "Course Lists"
    name: "course-lists"
    fields:
      - label: Draft
        name: draft
        required: true
        widget: boolean
        help: Enable this setting to prevent publishing in production

      - label: Title
        name: title
        widget: string
        required: true

      - label: Description
        name: description
        widget: markdown

      - label: Courses
        name: courses
        widget: website-collection

  - category: Content
    folder: content/collections
    label: "Course Collections"
    name: "course-collection"
    fields:
      - label: "Description"
        name: "description"
        widget: "markdown"
      - label: Cover Image
        name: cover-image
        widget: relation
        collection: resource
        display_field: title
        multiple: false
        filter:
          field: "resourcetype"
          filter_type: "equals"
          value: "Image"

      - label: Featured Courses List
        name: featured-courses
        widget: relation
        multiple: false
        collection: course-lists
        display_field: title
        sortable: false

      - label: Course Lists
        name: courselists
        widget: relation
        multiple: true
        collection: course-lists
        display_field: title
        sortable: true

  - category: Content
    folder: content/promos
    label: Promo
    name: promos
    fields:
      - label: Draft
        name: draft
        required: true
        widget: boolean
        help: Enable this setting to prevent publishing in production

      - label: Title
        name: title
        widget: string
        required: true

      - label: Subtitle
        name: subtitle
        widget: string

      - label: Link Title
        name: link_title
        widget: string

      - label: Url
        name: link_url
        widget: string

      - label: Image
        name: image
        widget: relation
        collection: resource
        display_field: title
        required: true
        multiple: false
        min: 1
        max: 1
        filter:
          field: "resourcetype"
          filter_type: "equals"
          value: "Image"

  - category: Content
    folder: content/notifications
    label: Notification
    name: notifications
    fields:
      - label: Draft
        name: draft
        required: true
        widget: boolean
        help: Enable this setting to prevent publishing in production

      - label: Title
        name: title
        widget: string
        required: true

      - label: Body
        name: body
        widget: markdown

      - label: Headless
        name: headless
        widget: hidden
        default: true

  - category: Content
    folder: content/stories
    label: Stories
    name: stories
    fields:
      - label: Draft
        name: draft
        required: true
        widget: boolean
        help: Enable this setting to prevent publishing in production

      - label: Title
        name: title
        widget: string
        required: true

      - label: Name
        name: name
        widget: string

      - label: Location
        name: location
        widget: string

      - label: Occupation
        name: occupation
        widget: string

      - label: Image
        name: image
        widget: relation
        collection: resource
        display_field: title
        multiple: false
        min: 1
        max: 1
        filter:
          field: "resourcetype"
          filter_type: "equals"
          value: "Image"

      - label: Lead Quote
        name: leadquote
        widget: string

      - label: Body
        name: body
        widget: markdown
        minimal: false

  - category: Content
    folder: content/resources
    label: Resources
    name: resource
    fields:
      - label: Draft
        name: draft
        required: true
        widget: boolean
        help: Enable this setting to prevent publishing in production

      - label: Title
        name: title
        required: true
        widget: string
      - label: Description
        name: description
        widget: markdown
      - label: Resource Type
        name: resourcetype
        required: true
        widget: select
        options:
          - Image
          - Video
          - Document
          - Other
      - label: File
        name: file
        widget: file

      # show the field below only if the type of resource is "image"
      - label: Image Metadata
        name: metadata
        widget: object
        condition: { field: resourcetype, equals: Image }
        fields:
          - label: ALT text
            name: image_alt
            widget: string
          - label: Caption
            name: caption
            widget: string
          - label: Credit
            name: credit
            widget: text

  - category: Content
    folder: content/instructors
    label: Instructor
    name: instructor
    slug: text_id
    fields:
      - label: Draft
        name: draft
        required: true
        widget: boolean
        help: Enable this setting to prevent publishing in production

      - label: First name
        name: first_name
        widget: string
        required: true

      - label: Middle initial
        name: middle_initial
        widget: string
        required: false

      - label: Last name
        name: last_name
        widget: string
        required: true

      - label: Salutation
        name: salutation
        widget: string
        required: false

      - label: Headless
        name: headless
        widget: hidden
        default: true

  - category: Settings
    label: Menu
    name: menu
    files:
      - file: config/_default/menus.yaml
        name: navmenu
        label: Navigation Menu
        fields:
          - { "label": "Menu", "name": "mainmenu", "widget": "menu" }
