version: '3.7'
services:
  web:
    volumes:
      - .:/src
      - django_media:/var/media
    environment:
      DEBUG: 'True'
      NODE_ENV: 'development'
      WEBPACK_USE_DEV_SERVER: 'True'
      WEBPACK_DEV_SERVER_PORT: 8042

  celery:
    volumes:
      - .:/src
      - django_media:/var/media
    environment:
      DEBUG: 'True'
      NODE_ENV: 'development'
      WEBPACK_USE_DEV_SERVER: 'True'
      WEBPACK_DEV_SERVER_PORT: 8042

  nginx:
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/src

  watch:
    volumes:
      - .:/src
      - yarn-cache:/home/mitodl/.cache/yarn
    environment:
      NODE_ENV: 'development'

volumes:
  django_media: {}
  yarn-cache: {}
