version: '3.7'

x-environment:
  &py-enviroment
  DEBUG: 'False'
  NODE_ENV: 'production'
  DEV_ENV: 'True'  # necessary to have nginx connect to web container
  SECRET_KEY: local_unsafe_key  # pragma: allowlist secret
  DATABASE_URL: postgres://postgres:postgres@db:5432/postgres  # pragma: allowlist secret
  OCW_STUDIO_SECURE_SSL_REDIRECT: 'False'
  OCW_STUDIO_DB_DISABLE_SSL: 'True'
  CELERY_TASK_ALWAYS_EAGER: 'False'
  CELERY_BROKER_URL: redis://redis:6379/4
  CELERY_RESULT_BACKEND: redis://redis:6379/4
  DOCKER_HOST: ${DOCKER_HOST:-missing}
  WEBPACK_DEV_SERVER_HOST: ${WEBPACK_DEV_SERVER_HOST:-localhost}
  DJANGO_SETTINGS_MODULE: "main.settings"
  PYTHONPATH: "."

networks:
  default-network:
    driver: bridge
  concourse-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/24"
services:
  db:
    image: postgres:12.8
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres  # pragma: allowlist secret
    networks:
      default-network:
      concourse-network:
        ipv4_address: 10.1.0.103

  redis:
    image: redis:6.0.10
    ports:
      - "6379"
    networks:
     - default-network
     - concourse-network

  nginx:
    image: nginx:1.22.0
    environment:
      AWS_PREVIEW_BUCKET_NAME: $AWS_PREVIEW_BUCKET_NAME
      AWS_PUBLISH_BUCKET_NAME: $AWS_PUBLISH_BUCKET_NAME
    ports:
      - "8043:8043"
      - "8044:8044"
      - "8045:8045"
    links:
      - web
      - s3
    networks:
      default-network:
      concourse-network:
        ipv4_address: 10.1.0.102

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/bash -c '
      sleep 3 &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py migrate --noinput &&
      uwsgi uwsgi.ini --honour-stdin'
    stdin_open: true
    tty: true
    ports:
      - "8041:8041"
    environment:
      << : *py-enviroment
      PORT: 8041
    env_file: .env
    links:
      - db
      - redis
    networks:
      - default-network
      - concourse-network

  watch:
    image: node:16.15.0
    working_dir: /src
    command: >
      /bin/bash -c './webpack_dev_server.sh --install'
    ports:
      - "8042:8042"
    environment:
      NODE_ENV: 'production'
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      CONTAINER_NAME: 'watch'
    env_file: .env
    networks:
      - default-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment: *py-enviroment
    env_file: .env
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A main.celery:app worker -Q publish,batch,default, -B -l ${OCW_STUDIO_LOG_LEVEL:-INFO}'
    links:
      - db
      - redis
    networks:
      - default-network
      - concourse-network

  concourse-db:
    image: postgres:11.6
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: postgres
      PGDATA: /database
    networks:
      - default-network

  concourse:
    image: concourse/concourse:7.7.1
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    stdin_open: true
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: postgres
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_URL:-http://concourse:8080}
      CONCOURSE_ADD_LOCAL_USER: ${CONCOURSE_USER_NAME:-test}:${CONCOURSE_PASSWORD:-test}  # pragma: allowlist secret
      CONCOURSE_MAIN_TEAM_LOCAL_USER: ${CONCOURSE_USER_NAME:-test}
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: ocw
      CONCOURSE_WORKER_CONTAINERD_DNS_SERVER: "8.8.8.8"
      CONCOURSE_CONTAINERD_ALLOW_HOST_ACCESS: "true"
      CONCOURSE_WORKER_RUNTIME: "containerd"
      CONCOURSE_ENABLE_PIPELINE_INSTANCES: "true"
      CONCOURSE_ENABLE_ACROSS_STEP: "true"
      CONCOURSE_CONTAINERD_MAX_CONTAINERS: 1200
    links:
      - web
      - nginx
      - s3
    networks:
      default-network:
      concourse-network:
        ipv4_address: 10.1.0.101

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./s3:/data
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      default-network:
      concourse-network:
        ipv4_address: 10.1.0.100
  create-buckets:
    image: minio/mc
    depends_on:
      s3:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      AWS_STORAGE_BUCKET_NAME: $AWS_STORAGE_BUCKET_NAME
      AWS_PREVIEW_BUCKET_NAME: $AWS_PREVIEW_BUCKET_NAME
      AWS_PUBLISH_BUCKET_NAME: $AWS_PUBLISH_BUCKET_NAME
      AWS_ARTIFACTS_BUCKET_NAME: $AWS_ARTIFACTS_BUCKET_NAME
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://10.1.0.100:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb minio/$AWS_STORAGE_BUCKET_NAME;
      /usr/bin/mc policy set public minio/$AWS_STORAGE_BUCKET_NAME;
      /usr/bin/mc mb minio/$AWS_PREVIEW_BUCKET_NAME;
      /usr/bin/mc policy set public minio/$AWS_PREVIEW_BUCKET_NAME;
      /usr/bin/mc mb minio/$AWS_PUBLISH_BUCKET_NAME;
      /usr/bin/mc policy set public minio/$AWS_PUBLISH_BUCKET_NAME;
      /usr/bin/mc mb minio/$AWS_ARTIFACTS_BUCKET_NAME;
      /usr/bin/mc policy set public minio/$AWS_ARTIFACTS_BUCKET_NAME;
      /usr/bin/mc version enable minio/$AWS_ARTIFACTS_BUCKET_NAME;
      "
    networks:
      - concourse-network
