FROM node:15.14.0
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

COPY package.json /src/

COPY scripts /src/scripts

RUN mkdir -p /home/node/.cache/yarn

RUN chown node:node /home/node/.cache/yarn
RUN chown node:node /src/

USER node

WORKDIR /src/
