FROM node:15.9.0
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

COPY package.json /src/

COPY scripts /src/scripts

RUN mkdir -p /home/node/.cache/yarn

RUN chown node:node /home/node/.cache/yarn
RUN chown node:node /src/

USER node

WORKDIR /src/
