# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.


# >>> aqueduct:generated:imports
from __future__ import annotations

import ast
import json
import logging
import platform
from typing import Annotated, Any

from main.envs import get_dict_of_str
from mitol.common.envs import get_features, get_site_name, get_string
from pydantic import AliasChoices, Field, field_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict

# <<< aqueduct:generated:imports

# Hand-maintained imports used by the preserved regions below (kept outside
# the generated region so regeneration never touches them).
import os
from ast import literal_eval
from pathlib import Path
from typing import Annotated
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from django_aqueduct import derivations as dv
from django_aqueduct.sources.dev import vault_source_from_env
from pydantic import field_validator, model_validator
from pydantic_settings import NoDecode

from main.constants import PRODUCTION_NAMES

# Django's built-in default (django.conf.global_settings.STORAGES); declared
# explicitly so STORAGES is a real model field instead of relying on
# extra="allow" injection from a validator.
_DJANGO_DEFAULT_STORAGES: dict[str, Any] = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


def _feature_bool(name: str, value: Any) -> bool:
    """Parse a feature-flag value as a boolean, mirroring EnvParser.get_bool."""
    if isinstance(value, bool):
        return value
    parsed = str(value).strip().lower()
    if parsed == "true":
        return True
    if parsed == "false":
        return False
    msg = f"Expected value in FEATURE_{name}={value} to be a boolean"
    raise ImproperlyConfigured(msg)


class AqueductSettings(BaseSettings):
    """Typed Django settings model generated by django-aqueduct."""

    model_config = SettingsConfigDict(env_prefix="", extra="allow")

    # >>> aqueduct:generated:fields
    # ===== main.settings =====
    ADMINS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ADMIN_EMAIL: str = Field(
        default="",
        validation_alias=AliasChoices("OCW_STUDIO_ADMIN_EMAIL"),
        description="e-mail configurable admins",
    )
    ALLOWED_HOSTS: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ["*"])
    ANYMAIL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    API_BEARER_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("API_BEARER_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    ARCHIVE_URL_REQUEST_TIMEOUT: int = Field(
        default=120, validation_alias=AliasChoices("ARCHIVE_URL_REQUEST_TIMEOUT")
    )
    AUTHENTICATION_BACKENDS: tuple[Any, ...] = Field(
        default=(
            "social_core.backends.keycloak.KeycloakOAuth2",
            "django.contrib.auth.backends.ModelBackend",
            "guardian.backends.ObjectPermissionBackend",
        ),
    )  # TODO: refine type
    AUTH_USER_MODEL: str = Field(
        default="users.User", description="configure a custom user model"
    )
    AWS_ACCESS_KEY_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_ACCESS_KEY_ID")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AWS_ACCOUNT_ID: str = Field(..., validation_alias=AliasChoices("AWS_ACCOUNT_ID"))
    AWS_ARTIFACTS_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_ARTIFACTS_BUCKET_NAME")
    )
    AWS_DEFAULT_ACL: str = Field(default="public-read")
    AWS_IMPORT_STORAGE_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_IMPORT_STORAGE_BUCKET_NAME")
    )
    AWS_MAX_CONCURRENT_CONNECTIONS: int = Field(
        default=10, validation_alias=AliasChoices("AWS_MAX_CONCURRENT_CONNECTIONS")
    )
    AWS_OFFLINE_PREVIEW_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_OFFLINE_PREVIEW_BUCKET_NAME")
    )
    AWS_OFFLINE_PUBLISH_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_OFFLINE_PUBLISH_BUCKET_NAME")
    )
    AWS_OFFLINE_TEST_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_OFFLINE_TEST_BUCKET_NAME")
    )
    AWS_PREVIEW_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_PREVIEW_BUCKET_NAME")
    )
    AWS_PUBLISH_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_PUBLISH_BUCKET_NAME")
    )
    AWS_QUERYSTRING_AUTH: bool = Field(
        default=False, validation_alias=AliasChoices("AWS_QUERYSTRING_AUTH")
    )
    AWS_REGION: str = Field(
        default="us-east-1", validation_alias=AliasChoices("AWS_REGION")
    )
    AWS_ROLE_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_ROLE_NAME")
    )
    AWS_S3_SYNC_INTERVAL: str = Field(
        default="24h", validation_alias=AliasChoices("AWS_S3_SYNC_INTERVAL")
    )
    AWS_SECRET_ACCESS_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_SECRET_ACCESS_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AWS_STORAGE_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_STORAGE_BUCKET_NAME")
    )
    AWS_TEST_BUCKET_NAME: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_TEST_BUCKET_NAME")
    )
    BASE_DIR: Any = Field(
        default=None,
        description="Build paths inside the project like this: os.path.join(BASE_DIR, ...)",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CACHES: Any = Field(
        default=None, description="django cache back-ends"
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_ACCEPT_CONTENT: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["json"]
    )
    CELERY_BEAT_SCHEDULE: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_BROKER_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("CELERY_BROKER_URL")
    )  # REDACTED: name looks secret-like — set via a source, not here
    CELERY_RESULT_BACKEND: str | None = Field(
        default=None, validation_alias=AliasChoices("CELERY_RESULT_BACKEND")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_RESULT_SERIALIZER: str = Field(default="json")
    CELERY_TASK_ALWAYS_EAGER: bool = Field(
        default=False, validation_alias=AliasChoices("CELERY_TASK_ALWAYS_EAGER")
    )
    CELERY_TASK_EAGER_PROPAGATES: bool = Field(
        default=True, validation_alias=AliasChoices("CELERY_TASK_EAGER_PROPAGATES")
    )
    CELERY_TASK_SERIALIZER: str = Field(default="json")
    CELERY_TIMEZONE: str = Field(default="UTC")
    CHECK_EXTERNAL_RESOURCE_STATUS_FREQUENCY: int = Field(
        default=604800,
        validation_alias=AliasChoices("CHECK_EXTERNAL_RESOURCE_STATUS_FREQUENCY"),
        description="Check External Resources settings",
    )
    CONCOURSE_HARD_PURGE: bool = Field(
        default=True, validation_alias=AliasChoices("CONCOURSE_HARD_PURGE")
    )
    CONCOURSE_IS_PRIVATE_REPO: bool = Field(
        default=True, validation_alias=AliasChoices("CONCOURSE_IS_PRIVATE_REPO")
    )
    CONCOURSE_PASSWORD: str | None = Field(
        default=None, validation_alias=AliasChoices("CONCOURSE_PASSWORD")
    )  # REDACTED: name looks secret-like — set via a source, not here
    CONCOURSE_TEAM: str = Field(
        default="ocw", validation_alias=AliasChoices("CONCOURSE_TEAM")
    )
    CONCOURSE_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("CONCOURSE_URL"),
        description="Concourse-CI settings",
    )
    CONCOURSE_USERNAME: str | None = Field(
        default=None, validation_alias=AliasChoices("CONCOURSE_USERNAME")
    )
    CONTENT_FILE_SEARCH_API_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("CONTENT_FILE_SEARCH_API_URL")
    )
    CONTENT_SYNC_BACKEND: str | None = Field(
        default=None, validation_alias=AliasChoices("CONTENT_SYNC_BACKEND")
    )
    CONTENT_SYNC_PIPELINE_BACKEND: str = Field(
        default="concourse",
        validation_alias=AliasChoices("CONTENT_SYNC_PIPELINE_BACKEND"),
    )
    CONTENT_SYNC_RETRIES: int = Field(
        default=5, validation_alias=AliasChoices("CONTENT_SYNC_RETRIES")
    )
    COURSE_SEARCH_API_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("COURSE_SEARCH_API_URL")
    )
    DATABASES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEBUG: bool = Field(
        default=False,
        validation_alias=AliasChoices("DEBUG"),
        description="SECURITY WARNING: don't run with debug turned on in production!",
    )
    DEFAULT_AUTO_FIELD: str = Field(default="django.db.models.AutoField")
    DEFAULT_DATABASE_CONFIG: Any = Field(
        default=None,
        description="Database\nhttps://docs.djangoproject.com/en/2.0/ref/settings/#databases",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DISABLE_WEBPACK_LOADER_STATS: bool = Field(
        default=False, validation_alias=AliasChoices("DISABLE_WEBPACK_LOADER_STATS")
    )
    DJANGO_LOG_LEVEL: str = Field(
        default="INFO", validation_alias=AliasChoices("DJANGO_LOG_LEVEL")
    )
    DJANGO_REDIS_CLOSE_CONNECTION: bool = Field(default=True)
    DRIVE_S3_UPLOAD_PREFIX: str = Field(
        default="gdrive_uploads",
        validation_alias=AliasChoices("DRIVE_S3_UPLOAD_PREFIX"),
    )
    DRIVE_SERVICE_ACCOUNT_CREDS: str | None = Field(
        default=None,
        validation_alias=AliasChoices("DRIVE_SERVICE_ACCOUNT_CREDS"),
        description="Google Drive and Video settings",
    )
    DRIVE_SHARED_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("DRIVE_SHARED_ID")
    )
    DRIVE_UPLOADS_PARENT_FOLDER_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("DRIVE_UPLOADS_PARENT_FOLDER_ID")
    )
    ENABLE_CHECK_EXTERNAL_RESOURCE_TASK: bool = Field(
        default=True,
        validation_alias=AliasChoices("CHECK_EXTERNAL_RESOURCE_TASK_STATUS"),
    )
    ENABLE_WAYBACK_TASKS: bool = Field(
        default=False,
        validation_alias=AliasChoices("ENABLE_WAYBACK_TASKS"),
        description="Wayback Machine Settings",
    )
    ENVIRONMENT: str = Field(
        ...,
        validation_alias=AliasChoices("OCW_STUDIO_ENVIRONMENT"),
        description="Sentry",
    )
    ENV_NAME: str = Field(default="rc", validation_alias=AliasChoices("ENV_NAME"))
    FEATURES: Any = Field(default_factory=lambda: get_features())  # TODO: refine type
    FEATURES_DEFAULT: bool = Field(
        default=False, validation_alias=AliasChoices("FEATURES_DEFAULT")
    )
    FIELD_METADATA_TITLE: str = Field(
        default="course_title", validation_alias=AliasChoices("FIELD_METADATA_TITLE")
    )
    FIELD_RESOURCETYPE: str = Field(
        default="resourcetype",
        validation_alias=AliasChoices("FIELD_RESOURCETYPE"),
        description="OCW metadata fields",
    )
    GA_TRACKING_ID: str = Field(
        default="", validation_alias=AliasChoices("GA_TRACKING_ID")
    )
    GITHUB_APP_ID: int | None = Field(
        default=None, validation_alias=AliasChoices("GITHUB_APP_ID")
    )
    GITHUB_APP_PRIVATE_KEY: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    GITHUB_RATE_LIMIT_CHECK: bool = Field(
        default=False, validation_alias=AliasChoices("GITHUB_RATE_LIMIT_CHECK")
    )
    GITHUB_RATE_LIMIT_CUTOFF: int = Field(
        default=100, validation_alias=AliasChoices("GITHUB_RATE_LIMIT_CUTOFF")
    )
    GITHUB_RATE_LIMIT_MIN_SLEEP: int = Field(
        default=5, validation_alias=AliasChoices("GITHUB_RATE_LIMIT_MIN_SLEEP")
    )
    GITHUB_TIMEOUT: int = Field(
        default=15, validation_alias=AliasChoices("GITHUB_TIMEOUT")
    )
    GITHUB_WEBHOOK_BRANCH: str = Field(
        default="", validation_alias=AliasChoices("GITHUB_WEBHOOK_BRANCH")
    )
    GITHUB_WEBHOOK_KEY: str = Field(
        default="", validation_alias=AliasChoices("GITHUB_WEBHOOK_KEY")
    )
    GIT_API_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("GIT_API_URL")
    )
    GIT_BRANCH_MAIN: str = Field(
        default="main", validation_alias=AliasChoices("GIT_BRANCH_MAIN")
    )
    GIT_BRANCH_PREVIEW: str = Field(
        default="preview", validation_alias=AliasChoices("GIT_BRANCH_PREVIEW")
    )
    GIT_BRANCH_RELEASE: str = Field(
        default="release", validation_alias=AliasChoices("GIT_BRANCH_RELEASE")
    )
    GIT_DEFAULT_USER_EMAIL: str = Field(
        default="anonymous@example.edu",
        validation_alias=AliasChoices("GIT_DEFAULT_USER_EMAIL"),
    )
    GIT_DEFAULT_USER_NAME: str = Field(
        default="Anonymous", validation_alias=AliasChoices("GIT_DEFAULT_USER_NAME")
    )
    GIT_DOMAIN: str = Field(
        default="www.github.com", validation_alias=AliasChoices("GIT_DOMAIN")
    )
    GIT_ORGANIZATION: str | None = Field(
        default=None, validation_alias=AliasChoices("GIT_ORGANIZATION")
    )
    GIT_TOKEN: str | None = Field(
        default=None,
        validation_alias=AliasChoices("GIT_TOKEN"),
        description="Git backend settings",
    )  # REDACTED: name looks secret-like — set via a source, not here
    HEALTH_CHECK: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["CELERY", "REDIS", "POSTGRES"]
    )
    HEROKU_APP_NAME: str | None = Field(
        default=None,
        validation_alias=AliasChoices("HEROKU_APP_NAME"),
        description="this is only available to heroku review apps",
    )
    HIJACK_ALLOW_GET_REQUESTS: bool = Field(default=True)
    HIJACK_LOGIN_REDIRECT_URL: str = Field(default="sites")
    HIJACK_LOGOUT_REDIRECT_URL: str = Field(default="/admin/users/user/")
    HIJACK_REGISTER_ADMIN: bool = Field(default=False)
    HOSTNAME: Any = Field(
        default_factory=lambda: platform.node().split(".")[0]
    )  # TODO: refine type
    INSTALLED_APPS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            "django.contrib.sites",
            "guardian",
            "hijack",
            "hijack.contrib.admin",
            "safedelete",
            "rest_framework",
            "social_django",
            "robots",
            "anymail",
            "bulk_update_or_create",
            "main",
            "users",
            "websites",
            "news",
            "content_sync",
            "gdrive_sync",
            "videos",
            "external_resources",
            "django_removals",
            "django_aqueduct",
            "mitol.common.apps.CommonApp",
            "mitol.authentication.apps.AuthenticationApp",
            "mitol.mail.apps.MailApp",
        ],
        description="Application definition",
    )
    INTERNAL_IPS: Any = Field(
        default_factory=lambda: (
    get_string(
        name="HOST_IP", default="127.0.0.1", description="This server's host IP"
    ),
),
        description="Important to define this so DEBUG works properly",
    )  # TODO: refine type
    LANGUAGE_CODE: str = Field(default="en-us")
    LOGGING: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    LOGIN_ERROR_URL: str = Field(default="/")
    LOGIN_REDIRECT_URL: str = Field(default="/")
    LOGIN_URL: str = Field(default="/")
    LOGOUT_REDIRECT_URL: str = Field(default="/")
    LOG_HOST: str = Field(
        default="localhost",
        validation_alias=AliasChoices("OCW_STUDIO_LOG_HOST"),
        description="For logging to a remote syslog host",
    )
    LOG_HOST_PORT: int = Field(
        default=514, validation_alias=AliasChoices("OCW_STUDIO_LOG_HOST_PORT")
    )
    LOG_LEVEL: str = Field(
        default="INFO",
        validation_alias=AliasChoices("OCW_STUDIO_LOG_LEVEL"),
        description="Logging configuration",
    )
    MAILGUN_KEY: str = Field(..., validation_alias=AliasChoices("MAILGUN_KEY"))
    MAILGUN_SENDER_DOMAIN: str = Field(
        ...,
        validation_alias=AliasChoices("MAILGUN_SENDER_DOMAIN"),
        description="mitol-django-mail",
    )
    MAX_S3_GET_ITERATIONS: int = Field(
        default=3, validation_alias=AliasChoices("MAX_S3_GET_ITERATIONS")
    )
    MEDIA_ROOT: str = Field(
        default="/var/media/", validation_alias=AliasChoices("MEDIA_ROOT")
    )
    MEDIA_URL: str = Field(default="/media/")
    MIDDLEWARE: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "django.contrib.sites.middleware.CurrentSiteMiddleware",
            "main.middleware.CachelessAPIMiddleware",
            "hijack.middleware.HijackUserMiddleware",
        ],
    )
    MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS: int = Field(
        default_factory=lambda: 60 * 60,
        validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS"),
    )
    MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME: str = Field(
        default="OCW_STUDIO_FEATURE_FLAGS",
        validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME"),
    )
    MIDDLEWARE_FEATURE_FLAG_QS_PREFIX: str | None = Field(
        default=None, validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_QS_PREFIX")
    )
    MITOL_MAIL_ENABLE_EMAIL_DEBUGGER: bool | None = Field(
        default=None, validation_alias=AliasChoices("MITOL_MAIL_ENABLE_EMAIL_DEBUGGER")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MITOL_MAIL_FORMAT_RECIPIENT_FUNC: str = Field(
        default="users.utils.format_recipient",
        validation_alias=AliasChoices("MITOL_MAIL_FORMAT_RECIPIENT_FUNC"),
    )
    MITOL_MAIL_FROM_EMAIL: str = Field(
        default="webmaster@localhost",
        validation_alias=AliasChoices("MITOL_MAIL_FROM_EMAIL"),
    )
    MITOL_MAIL_MESSAGE_CLASSES: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "videos.messages.YouTubeUploadSuccessMessage",
            "videos.messages.YouTubeUploadFailureMessage",
            "websites.messages.PreviewOrPublishSuccessMessage",
            "websites.messages.PreviewOrPublishFailureMessage",
            "websites.messages.videoTranscriptingCompleteMessage",
        ],
    )
    MITOL_MAIL_RECIPIENT_OVERRIDE: str | None = Field(
        default=None, validation_alias=AliasChoices("MITOL_MAIL_RECIPIENT_OVERRIDE")
    )
    MITOL_MAIL_REPLY_TO_ADDRESS: str = Field(
        default="webmaster@localhost",
        validation_alias=AliasChoices("MITOL_MAIL_REPLY_TO_ADDRESS"),
    )
    MIT_LEARN_API_BASE_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("MIT_LEARN_API_BASE_URL")
    )
    MIT_LEARN_BASE_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("MIT_LEARN_BASE_URL")
    )
    NPLUSONE_LOGGER: Any = Field(
        default_factory=lambda: logging.getLogger("nplusone"),
        description="nplusone profiler logger configuration",
    )  # TODO: refine type
    NPLUSONE_LOG_LEVEL: Any = Field(
        default_factory=lambda: logging.ERROR
    )  # TODO: refine type
    OCW_COURSE_STARTER_SLUG: str = Field(
        default="course", validation_alias=AliasChoices("OCW_COURSE_STARTER_SLUG")
    )
    OCW_DEFAULT_COURSE_THEME: str = Field(
        default="ocw-course-v2",
        validation_alias=AliasChoices("OCW_DEFAULT_COURSE_THEME"),
    )
    OCW_EXTRA_COURSE_THEMES: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("OCW_EXTRA_COURSE_THEMES"),
    )
    OCW_EXTRA_THEMES_BASE_URLS: Any = Field(
        default_factory=lambda: get_dict_of_str(
    name="OCW_EXTRA_THEMES_BASE_URLS",
    default={},
),
    )  # TODO: refine type
    OCW_EXTRA_THEMES_GTM_IDS: Any = Field(
        default_factory=lambda: get_dict_of_str(
    name="OCW_EXTRA_THEMES_GTM_IDS",
    default={},
),
    )  # TODO: refine type
    OCW_GTM_ACCOUNT_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("OCW_GTM_ACCOUNT_ID")
    )
    OCW_HUGO_PROJECTS_BRANCH: str | None = Field(
        default=None, validation_alias=AliasChoices("OCW_HUGO_PROJECTS_BRANCH")
    )
    OCW_HUGO_THEMES_BRANCH: str | None = Field(
        default=None, validation_alias=AliasChoices("OCW_HUGO_THEMES_BRANCH")
    )
    OCW_HUGO_THEMES_SENTRY_DSN: str | None = Field(
        default=None, validation_alias=AliasChoices("OCW_HUGO_THEMES_SENTRY_DSN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    OCW_IMPORT_STARTER_SLUG: str = Field(
        default="course", validation_alias=AliasChoices("OCW_IMPORT_STARTER_SLUG")
    )
    OCW_MASS_BUILD_BATCH_SIZE: int = Field(
        default=20, validation_alias=AliasChoices("OCW_MASS_BUILD_BATCH_SIZE")
    )
    OCW_MASS_BUILD_MAX_IN_FLIGHT: int = Field(
        default=10, validation_alias=AliasChoices("OCW_MASS_BUILD_MAX_IN_FLIGHT")
    )
    OCW_STUDIO_DELETABLE_CONTENT_TYPES: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("OCW_STUDIO_DELETABLE_CONTENT_TYPES"),
    )
    OCW_STUDIO_DRAFT_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("OCW_STUDIO_DRAFT_URL")
    )
    OCW_STUDIO_LIVE_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("OCW_STUDIO_LIVE_URL")
    )
    OCW_STUDIO_SITE_CONFIG_FILE: str = Field(
        default="ocw-studio.yaml",
        validation_alias=AliasChoices("OCW_STUDIO_SITE_CONFIG_FILE"),
    )
    OCW_STUDIO_TEST_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("OCW_STUDIO_TEST_URL")
    )
    OCW_STUDIO_USE_S3: bool = Field(
        default=False, validation_alias=AliasChoices("OCW_STUDIO_USE_S3")
    )
    OCW_TEST_SITE_SLUGS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [], validation_alias=AliasChoices("OCW_TEST_SITE_SLUGS")
    )
    OPEN_CATALOG_URLS: Annotated[list[str], NoDecode] = Field(
        default="", validation_alias=AliasChoices("OPEN_CATALOG_URLS")
    )
    OPEN_CATALOG_WEBHOOK_KEY: str = Field(
        default="", validation_alias=AliasChoices("OPEN_CATALOG_WEBHOOK_KEY")
    )
    PLAYWRIGHT_IMAGE_ARCH: str = Field(
        default="", validation_alias=AliasChoices("PLAYWRIGHT_IMAGE_ARCH")
    )
    POSTHOG_API_HOST: str = Field(
        default="https://app.posthog.com",
        validation_alias=AliasChoices("POSTHOG_API_HOST"),
    )
    POSTHOG_ENABLED: bool = Field(
        default=False, validation_alias=AliasChoices("POSTHOG_ENABLED")
    )
    POSTHOG_FEATURE_FLAG_REQUEST_TIMEOUT_MS: int = Field(
        default=3000,
        validation_alias=AliasChoices("POSTHOG_FEATURE_FLAG_REQUEST_TIMEOUT_MS"),
    )
    POSTHOG_MAX_RETRIES: int = Field(
        default=3, validation_alias=AliasChoices("POSTHOG_MAX_RETRIES")
    )
    POSTHOG_PROJECT_API_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("POSTHOG_PROJECT_API_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    PREPUBLISH_ACTIONS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [], validation_alias=AliasChoices("PREPUBLISH_ACTIONS")
    )
    PUBLISH_INCOMPLETE_BUILD_STATUS_FREQUENCY: int = Field(
        default=1800,
        validation_alias=AliasChoices("PUBLISH_INCOMPLETE_BUILD_STATUS_FREQUENCY"),
    )
    PUBLISH_POSTHOG_API_HOST: str = Field(
        default="https://app.posthog.com",
        validation_alias=AliasChoices("PUBLISH_POSTHOG_API_HOST"),
    )
    PUBLISH_POSTHOG_ENABLED: bool = Field(
        default=False, validation_alias=AliasChoices("PUBLISH_POSTHOG_ENABLED")
    )
    PUBLISH_POSTHOG_FEATURE_FLAG_REQUEST_TIMEOUT_MS: int = Field(
        default=3000,
        validation_alias=AliasChoices("PUBLISH_POSTHOG_FEATURE_FLAG_REQUEST_TIMEOUT_MS"),  # noqa: E501
    )
    PUBLISH_POSTHOG_MAX_RETRIES: int = Field(
        default=3, validation_alias=AliasChoices("PUBLISH_POSTHOG_MAX_RETRIES")
    )
    PUBLISH_POSTHOG_PROJECT_API_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("PUBLISH_POSTHOG_PROJECT_API_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    PUBLISH_STATUS_CUTOFF: int = Field(
        default=1800, validation_alias=AliasChoices("PUBLISH_STATUS_CUTOFF")
    )
    PUBLISH_STATUS_WAIT_TIME: int = Field(
        default=600,
        validation_alias=AliasChoices("PUBLISH_STATUS_WAIT_TIME"),
        description="Publish status settings",
    )
    REACT_GA_DEBUG: bool = Field(
        default=False, validation_alias=AliasChoices("REACT_GA_DEBUG")
    )
    REDISCLOUD_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("REDISCLOUD_URL"),
        description="Celery",
    )
    REDIS_MAX_CONNECTIONS: int = Field(
        default=48, validation_alias=AliasChoices("REDIS_MAX_CONNECTIONS")
    )
    RESOURCE_BASE_URL_DRAFT: str = Field(
        default="", validation_alias=AliasChoices("RESOURCE_BASE_URL_DRAFT")
    )
    RESOURCE_BASE_URL_LIVE: str = Field(
        default="", validation_alias=AliasChoices("RESOURCE_BASE_URL_LIVE")
    )
    RESOURCE_TYPE_FIELDS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: ["resourcetype", "filetype"],
        validation_alias=AliasChoices("RESOURCE_TYPE_FIELDS"),
    )
    REST_FRAMEWORK: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "DEFAULT_PERMISSION_CLASSES": (
                "rest_framework.permissions.IsAuthenticated",
            ),
            "DEFAULT_AUTHENTICATION_CLASSES": (
                "rest_framework.authentication.SessionAuthentication",
            ),
            "TEST_REQUEST_DEFAULT_FORMAT": "json",
        },
    )
    ROBOTS_CACHE_TIMEOUT: int = Field(
        default_factory=lambda: 60 * 60 * 24,
        validation_alias=AliasChoices("ROBOTS_CACHE_TIMEOUT"),
    )
    ROBOTS_USE_HOST: bool = Field(default=False, description="django-robots")
    ROOT_URLCONF: str = Field(default="main.urls")
    ROOT_WEBSITE_NAME: str = Field(
        default="ocw-www", validation_alias=AliasChoices("ROOT_WEBSITE_NAME")
    )
    S3_TRANSCRIPTS_PREFIX: str = Field(
        default="transcript_files",
        validation_alias=AliasChoices("S3_TRANSCRIPTS_PREFIX"),
    )
    SEARCH_API_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("SEARCH_API_URL")
    )
    SECRET_KEY: str = Field(
        ...,
        validation_alias=AliasChoices("SECRET_KEY"),
        description="SECURITY WARNING: keep the secret key used in production secret!",
    )
    SECURE_PROXY_SSL_HEADER: tuple[Any, ...] = Field(
        default=("HTTP_X_FORWARDED_PROTO", "https")
    )  # TODO: refine type
    SECURE_SSL_REDIRECT: bool = Field(
        default=True, validation_alias=AliasChoices("OCW_STUDIO_SECURE_SSL_REDIRECT")
    )
    SENTRY_DSN: str | None = Field(
        default=None,
        validation_alias=AliasChoices("SENTRY_DSN"),
        description="initialize Sentry before doing anything else so we capture any config errors",  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    SENTRY_LOG_LEVEL: str = Field(
        default="ERROR", validation_alias=AliasChoices("SENTRY_LOG_LEVEL")
    )
    SESSION_ENGINE: str = Field(
        default="django.contrib.sessions.backends.signed_cookies"
    )
    SITEMAP_DOMAIN: str = Field(
        default="ocw.mit.edu", validation_alias=AliasChoices("SITEMAP_DOMAIN")
    )
    SITE_ID: int = Field(default=1, validation_alias=AliasChoices("OCW_STUDIO_SITE_ID"))
    SITE_NAME: Any = Field(default_factory=lambda: get_site_name())  # TODO: refine type
    SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: str = Field(
        ..., validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL")
    )
    SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: str = Field(
        ..., validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL")
    )
    SOCIAL_AUTH_KEYCLOAK_EXTRA_DATA: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [("id_token", "id_token")]
    )
    SOCIAL_AUTH_KEYCLOAK_KEY: str = Field(
        ...,
        validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_KEY"),
        description="Keycloak social auth settings",
    )
    SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY: str = Field(
        ..., validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY")
    )
    SOCIAL_AUTH_KEYCLOAK_SCOPE: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["openid", "profile", "email"]
    )
    SOCIAL_AUTH_KEYCLOAK_SECRET: str = Field(
        ..., validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_SECRET")
    )
    SOCIAL_AUTH_LOGIN_ERROR_URL: str = Field(default="main-index")
    SOCIAL_AUTH_LOGIN_REDIRECT_URL: str = Field(default="sites")
    SOCIAL_AUTH_PIPELINE: tuple[Any, ...] = Field(
        default=(
            "social_core.pipeline.social_auth.social_details",
            "social_core.pipeline.social_auth.social_uid",
            "social_core.pipeline.social_auth.auth_allowed",
            "social_core.pipeline.social_auth.social_user",
            "social_core.pipeline.user.get_username",
            "social_core.pipeline.social_auth.associate_by_email",
            "social_core.pipeline.user.create_user",
            "social_core.pipeline.social_auth.associate_user",
            "social_core.pipeline.social_auth.load_extra_data",
            "social_core.pipeline.user.user_details",
        ),
    )  # TODO: refine type
    SOCIAL_AUTH_USER_FIELD_MAPPING: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {"fullname": "name"}
    )
    STATICFILES_DIRS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    STATIC_API_BASE_URL_DRAFT: str = Field(
        default="", validation_alias=AliasChoices("STATIC_API_BASE_URL_DRAFT")
    )
    STATIC_API_BASE_URL_LIVE: str = Field(
        default="", validation_alias=AliasChoices("STATIC_API_BASE_URL_LIVE")
    )
    STATIC_API_BASE_URL_TEST: str = Field(
        default="", validation_alias=AliasChoices("STATIC_API_BASE_URL_TEST")
    )
    STATIC_ROOT: str = Field(default="staticfiles")
    STATIC_URL: str = Field(
        default="/static/", description="Serve static files with dj-static"
    )
    STATUS_TOKEN: str | None = Field(
        default=None,
        validation_alias=AliasChoices("STATUS_TOKEN"),
        description="server-status",
    )  # REDACTED: name looks secret-like — set via a source, not here
    STORAGES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    TEMPLATES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    TEST_ROOT_WEBSITE_NAME: str = Field(
        default="ocw-ci-test-www",
        validation_alias=AliasChoices("TEST_ROOT_WEBSITE_NAME"),
    )
    THREEPLAY_API_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("THREEPLAY_API_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    THREEPLAY_BASE_TIMEOUT: int = Field(
        default=15, validation_alias=AliasChoices("THREEPLAY_BASE_TIMEOUT")
    )
    THREEPLAY_CALLBACK_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("THREEPLAY_CALLBACK_KEY")
    )
    THREEPLAY_PROJECT_ID: int = Field(
        default=2, validation_alias=AliasChoices("THREEPLAY_PROJECT_ID")
    )
    TIME_ZONE: str = Field(default="UTC")
    UPDATE_MISSING_TRANSCRIPT_FREQUENCY: int = Field(
        default=43200,
        validation_alias=AliasChoices("UPDATE_MISSING_TRANSCRIPT_FREQUENCY"),
    )
    UPDATE_TAGGED_3PLAY_TRANSCRIPT_FREQUENCY: int = Field(
        default=3600,
        validation_alias=AliasChoices("UPDATE_TAGGED_3PLAY_TRANSCRIPT_FREQUENCY"),
    )
    UPDATE_WAYBACK_JOBS_STATUS_FREQUENCY: int = Field(
        default=21600,
        validation_alias=AliasChoices("UPDATE_WAYBACK_JOBS_STATUS_FREQUENCY"),
    )
    USE_I18N: bool = Field(default=True)
    USE_TZ: bool = Field(default=True)
    USE_X_FORWARDED_HOST: bool = Field(
        default=False, validation_alias=AliasChoices("USE_X_FORWARDED_HOST")
    )
    USE_X_FORWARDED_PORT: bool = Field(
        default=False, validation_alias=AliasChoices("USE_X_FORWARDED_PORT")
    )
    VERSION: str = Field(default="0.192.0")
    WAYBACK_MACHINE_ACCESS_KEY: str | None = Field(
        default=None,
        validation_alias=AliasChoices("WAYBACK_MACHINE_ACCESS_KEY"),
        description="Wayback Machine API Credentials",
    )  # REDACTED: name looks secret-like — set via a source, not here
    WAYBACK_MACHINE_SECRET_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("WAYBACK_MACHINE_SECRET_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    WAYBACK_SUBMISSION_INTERVAL_DAYS: int = Field(
        default=30, validation_alias=AliasChoices("WAYBACK_SUBMISSION_INTERVAL_DAYS")
    )
    WEBPACK_LOADER: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    WSGI_APPLICATION: str = Field(default="main.wsgi.application")
    YT_ACCESS_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("YT_ACCESS_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    YT_CATEGORY_ID: int = Field(
        default=27, validation_alias=AliasChoices("YT_CATEGORY_ID")
    )
    YT_CLIENT_ID: str = Field(default="", validation_alias=AliasChoices("YT_CLIENT_ID"))
    YT_CLIENT_SECRET: str | None = Field(
        default=None, validation_alias=AliasChoices("YT_CLIENT_SECRET")
    )  # REDACTED: name looks secret-like — set via a source, not here
    YT_FIELD_CAPTIONS: str = Field(
        default="video_files.video_captions_file",
        validation_alias=AliasChoices("YT_FIELD_CAPTIONS"),
        description="YouTube OCW metadata fields",
    )
    YT_FIELD_CAPTIONS_RESOURCE: str = Field(
        default="video_files.video_captions_resource",
        validation_alias=AliasChoices("YT_FIELD_CAPTIONS_RESOURCE"),
    )
    YT_FIELD_DESCRIPTION: str = Field(
        default="video_metadata.youtube_description",
        validation_alias=AliasChoices("YT_FIELD_DESCRIPTION"),
    )
    YT_FIELD_ID: str = Field(
        default="video_metadata.youtube_id",
        validation_alias=AliasChoices("YT_FIELD_ID"),
    )
    YT_FIELD_SPEAKERS: str = Field(
        default="video_metadata.video_speakers",
        validation_alias=AliasChoices("YT_FIELD_SPEAKERS"),
    )
    YT_FIELD_TAGS: str = Field(
        default="video_metadata.video_tags",
        validation_alias=AliasChoices("YT_FIELD_TAGS"),
    )
    YT_FIELD_THUMBNAIL: str = Field(
        default="video_files.video_thumbnail_file",
        validation_alias=AliasChoices("YT_FIELD_THUMBNAIL"),
    )
    YT_FIELD_TRANSCRIPT: str = Field(
        default="video_files.video_transcript_file",
        validation_alias=AliasChoices("YT_FIELD_TRANSCRIPT"),
    )
    YT_FIELD_TRANSCRIPT_RESOURCE: str = Field(
        default="video_files.video_transcript_resource",
        validation_alias=AliasChoices("YT_FIELD_TRANSCRIPT_RESOURCE"),
    )
    YT_PROJECT_ID: str = Field(
        default="", validation_alias=AliasChoices("YT_PROJECT_ID")
    )
    YT_REFRESH_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("YT_REFRESH_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    YT_STATUS_UPDATE_FREQUENCY: int = Field(
        default=60, validation_alias=AliasChoices("YT_STATUS_UPDATE_FREQUENCY")
    )
    YT_UPLOAD_FREQUENCY: int = Field(
        default=60, validation_alias=AliasChoices("YT_UPLOAD_FREQUENCY")
    )
    YT_UPLOAD_LIMIT: int = Field(
        default=50, validation_alias=AliasChoices("YT_UPLOAD_LIMIT")
    )
    # ===== mitol.common.settings.base =====
    SITE_BASE_URL: str = Field(...)
    # ===== mitol.common.settings.webpack =====
    WEBPACK_DEV_SERVER_HOST: str = Field(
        default="", validation_alias=AliasChoices("WEBPACK_DEV_SERVER_HOST")
    )
    WEBPACK_DEV_SERVER_PORT: int | None = Field(
        default=None, validation_alias=AliasChoices("WEBPACK_DEV_SERVER_PORT")
    )
    WEBPACK_DISABLE_LOADER_STATS: bool = Field(
        default=False, validation_alias=AliasChoices("WEBPACK_DISABLE_LOADER_STATS")
    )
    WEBPACK_USE_DEV_SERVER: bool = Field(
        default=False, validation_alias=AliasChoices("WEBPACK_USE_DEV_SERVER")
    )
    # ===== mitol.mail.settings.email =====
    DEFAULT_FROM_EMAIL: str = Field(default="webmaster@localhost")
    EMAIL_BACKEND: str = Field(default="django.core.mail.backends.smtp.EmailBackend")
    EMAIL_HOST: str = Field(default="localhost")
    EMAIL_HOST_PASSWORD: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    EMAIL_HOST_USER: str = Field(default="")
    EMAIL_PORT: int = Field(default=25)
    EMAIL_RECIPIENT_OVERRIDE: str | None = Field(
        default=None, validation_alias=AliasChoices("EMAIL_RECIPIENT_OVERRIDE")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    EMAIL_SUPPORT: str | None = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    EMAIL_USE_TLS: bool = Field(default=False)
    MAILGUN_RECIPIENT_OVERRIDE: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_RECIPIENT_OVERRIDE")
    )
    # ===== mitol.transcoding.settings.job =====
    POST_TRANSCODE_ACTIONS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("POST_TRANSCODE_ACTIONS"),
    )
    TRANSCODE_JOB_TEMPLATE: str = Field(
        default="", validation_alias=AliasChoices("TRANSCODE_JOB_TEMPLATE")
    )
    VIDEO_S3_THUMBNAIL_BUCKET: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_THUMBNAIL_BUCKET")
    )
    VIDEO_S3_THUMBNAIL_PREFIX: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_THUMBNAIL_PREFIX")
    )
    VIDEO_S3_TRANSCODE_BUCKET: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_TRANSCODE_BUCKET")
    )
    VIDEO_S3_TRANSCODE_ENDPOINT: str = Field(
        default="aws_mediaconvert_transcodes",
        validation_alias=AliasChoices("VIDEO_S3_TRANSCODE_ENDPOINT"),
    )
    VIDEO_S3_TRANSCODE_PREFIX: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_TRANSCODE_PREFIX")
    )
    VIDEO_S3_UPLOAD_PREFIX: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_UPLOAD_PREFIX")
    )
    VIDEO_TRANSCODE_QUEUE: str = Field(
        default="Default", validation_alias=AliasChoices("VIDEO_TRANSCODE_QUEUE")
    )
    # <<< aqueduct:generated:fields

    # >>> aqueduct:generated:container_decoders
    @field_validator(
        "ALLOWED_HOSTS",
        "CELERY_ACCEPT_CONTENT",
        "HEALTH_CHECK",
        "INSTALLED_APPS",
        "MIDDLEWARE",
        "MITOL_MAIL_MESSAGE_CLASSES",
        "OCW_EXTRA_COURSE_THEMES",
        "OCW_STUDIO_DELETABLE_CONTENT_TYPES",
        "OCW_TEST_SITE_SLUGS",
        "OPEN_CATALOG_URLS",
        "POST_TRANSCODE_ACTIONS",
        "PREPUBLISH_ACTIONS",
        "RESOURCE_TYPE_FIELDS",
        "SOCIAL_AUTH_KEYCLOAK_EXTRA_DATA",
        "SOCIAL_AUTH_KEYCLOAK_SCOPE",
        mode="before",
    )
    @classmethod
    def _aqueduct_decode_list_fields(cls, value: object) -> object:
        """Parse a list from a JSON, Python-literal, or comma-separated env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            try:
                parsed = ast.literal_eval(value)
            except (ValueError, SyntaxError):
                parsed = None
        if isinstance(parsed, list):
            return parsed
        stripped = value.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            stripped = stripped[1:-1].strip()
        if not stripped:
            return []
        return [item.strip() for item in stripped.split(",")]

    @field_validator("REST_FRAMEWORK", "SOCIAL_AUTH_USER_FIELD_MAPPING", mode="before")
    @classmethod
    def _aqueduct_decode_dict_fields(cls, value: object) -> object:
        """Parse a dict from a JSON or Python-literal env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            parsed = None
        if isinstance(parsed, dict):
            return parsed
        return ast.literal_eval(value)

    # <<< aqueduct:generated:container_decoders

    # >>> aqueduct:preserved:validators
    # ------------------------------------------------------------------
    # Overrides of generated fields. A later declaration in the class body
    # replaces the generated one above; these carry corrections static
    # discovery cannot know (mitol EnvParser runtime semantics, namespaced
    # env aliases, legacy defaults for settings whose required=True is only
    # enforced by env.validate()).
    # ------------------------------------------------------------------

    # mitol's get_string(required=True, default="dev") still returns the
    # default at read time; required-ness only matters to env.validate().
    ENVIRONMENT: str = Field(
        default="dev",
        validation_alias=AliasChoices("OCW_STUDIO_ENVIRONMENT"),
        description=(
            "The execution environment that the app is in (e.g. dev, staging, prod)"
        ),
    )
    # mitol get_string() without a default kwarg defaults to None.
    AWS_ACCOUNT_ID: str | None = Field(
        default=None,
        validation_alias=AliasChoices("AWS_ACCOUNT_ID"),
        description="AWS Account ID",
    )
    # Read inline in main/settings.py (never a module attribute there).
    DATABASE_URL: str = Field(
        default_factory=lambda: (
            f"sqlite:///{Path(__file__).resolve().parent.parent / 'db.sqlite3'}"
        ),
        validation_alias=AliasChoices("DATABASE_URL"),
        description="The connection url to the Postgres database",
    )
    HOST_IP: str = Field(
        default="127.0.0.1",
        validation_alias=AliasChoices("HOST_IP"),
        description="This server's host IP",
    )
    REDIS_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("REDIS_URL"),
        description="Redis URL for non-production use",
    )
    # Read inline off DEFAULT_DATABASE_CONFIG in main/settings.py, never module
    # attributes there, so static discovery cannot see them.
    OCW_STUDIO_DB_CONN_MAX_AGE: int = Field(
        default=0,
        validation_alias=AliasChoices("OCW_STUDIO_DB_CONN_MAX_AGE"),
        description="Maximum age of connection to Postgres in seconds",
    )
    OCW_STUDIO_DB_DISABLE_SS_CURSORS: bool = Field(
        default=True,
        validation_alias=AliasChoices("OCW_STUDIO_DB_DISABLE_SS_CURSORS"),
        description="Disables Postgres server side cursors",
    )
    OCW_STUDIO_DB_DISABLE_SSL: bool = Field(
        default=False,
        validation_alias=AliasChoices("OCW_STUDIO_DB_DISABLE_SSL"),
        description="Disables SSL to postgres if set to True",
    )
    # Injected into main/settings.py by init_app_settings().
    APP_SETTINGS_NAMESPACE: str = Field(
        default="OCW_STUDIO",
        validation_alias=AliasChoices("APP_SETTINGS_NAMESPACE"),
        description="App environment variable namespace",
    )
    SITE_NAME: str = Field(
        default="OCW Studio",
        validation_alias=AliasChoices("SITE_NAME"),
        description="Site name",
    )
    # app_namespaced() aliases are resolved at runtime in the mitol settings
    # modules, so the static scan cannot recover them.
    SITE_BASE_URL: str = Field(
        ...,
        validation_alias=AliasChoices("OCW_STUDIO_BASE_URL"),
        description=(
            "Base url for the application in the format PROTOCOL://HOSTNAME[:PORT]"
        ),
    )

    # NOTE: the *_URL/*_URI fields keep the plain `str` type static discovery
    # gives them. django-aqueduct 0.9.0 makes AnyUrl promotion opt-in
    # (`[tool.aqueduct] enrich_url_types`); it is deliberately left off here
    # because several of these feed in-model derivations that do string ops
    # (dv.first_url(REDISCLOUD_URL, ...) calls .strip(); CACHES LOCATION is
    # built from CELERY_BROKER_URL) and AnyUrl would also normalise a trailing
    # slash onto values like POSTHOG_API_HOST, changing the value legacy stores.
    EMAIL_BACKEND: str = Field(
        default="django.core.mail.backends.smtp.EmailBackend",
        validation_alias=AliasChoices("OCW_STUDIO_EMAIL_BACKEND"),
        description="The default email backend to use for outgoing email.",
    )
    EMAIL_HOST: str = Field(
        default="localhost",
        validation_alias=AliasChoices("OCW_STUDIO_EMAIL_HOST"),
        description="Outgoing e-mail hostname",
    )
    EMAIL_PORT: int = Field(
        default=25,
        validation_alias=AliasChoices("OCW_STUDIO_EMAIL_PORT"),
        description="Outgoing e-mail port",
    )
    EMAIL_HOST_USER: str = Field(
        default="",
        validation_alias=AliasChoices("OCW_STUDIO_EMAIL_USER"),
        description="Outgoing e-mail auth username",
    )
    EMAIL_HOST_PASSWORD: str = Field(
        default="",
        validation_alias=AliasChoices("OCW_STUDIO_EMAIL_PASSWORD"),
        description="Outgoing e-mail auth password",
    )
    EMAIL_USE_TLS: bool = Field(
        default=False,
        validation_alias=AliasChoices("OCW_STUDIO_EMAIL_TLS"),
        description="Outgoing e-mail TLS setting",
    )
    EMAIL_SUPPORT: str | None = Field(
        default=None,
        validation_alias=AliasChoices("OCW_STUDIO_SUPPORT_EMAIL"),
        description="Email address listed for customer support",
    )  # falls back to EMAIL_RECIPIENT_OVERRIDE or "support@localhost" below
    DEFAULT_FROM_EMAIL: str = Field(
        default="webmaster@localhost",
        validation_alias=AliasChoices("OCW_STUDIO_FROM_EMAIL"),
        description="E-mail to use for the from field",
    )
    # Secret-shaped names are generated with default=None, but the legacy
    # defaults are empty strings.
    SENTRY_DSN: str = Field(
        default="",
        validation_alias=AliasChoices("SENTRY_DSN"),
        description="The connection settings for Sentry",
    )
    STATUS_TOKEN: str = Field(
        default="",
        validation_alias=AliasChoices("STATUS_TOKEN"),
        description="Token to access the status API.",
    )
    YT_ACCESS_TOKEN: str = Field(
        default="",
        validation_alias=AliasChoices("YT_ACCESS_TOKEN"),
        description="Youtube access token",
    )
    YT_CLIENT_SECRET: str = Field(
        default="",
        validation_alias=AliasChoices("YT_CLIENT_SECRET"),
        description="Youtube client secret key",
    )
    YT_REFRESH_TOKEN: str = Field(
        default="",
        validation_alias=AliasChoices("YT_REFRESH_TOKEN"),
        description="YT_REFRESH_TOKEN",
    )
    # Holds the configured str; a bytes value once validated (matching the
    # unicode-escape roundtrip in main/settings.py). The transform below is
    # idempotent so re-validation of an already-bytes value is safe.
    GITHUB_APP_PRIVATE_KEY: str | bytes = Field(
        default="",
        validation_alias=AliasChoices("GITHUB_APP_PRIVATE_KEY"),
        description="A github app private key for authentication",
    )
    # A module-level constant in main/settings.py (imported from main.constants);
    # carried as a field so the model is a faithful superset of legacy settings.
    PRODUCTION_NAMES: set[str] = Field(default_factory=lambda: set(PRODUCTION_NAMES))
    HOSTNAME: str = Field(default_factory=lambda: platform.node().split(".")[0])
    INTERNAL_IPS: tuple[str, ...] = ()  # derived from HOST_IP below
    FEATURES: dict[str, bool] = Field(
        default_factory=dict,
        description=(
            "Feature flags collected from FEATURE_* environment variables and "
            "any FEATURE_* keys supplied by settings sources (e.g. Vault)"
        ),
    )
    # The comma-delimited mitol get_delimited_list fields (OPEN_CATALOG_URLS,
    # PREPUBLISH_ACTIONS, OCW_EXTRA_COURSE_THEMES,
    # OCW_STUDIO_DELETABLE_CONTENT_TYPES, RESOURCE_TYPE_FIELDS) are now typed and
    # parsed entirely by the generated `container_decoders` region above
    # (NoDecode + a JSON/literal/comma-split before-validator), so they no
    # longer need a hand-written override. OPEN_CATALOG_URLS's generated
    # default="" flows through that decoder to [""], matching legacy.

    # OCW_TEST_SITE_SLUGS (main/envs.py get_list_of_str) is now recognised as
    # list[str] by 0.9.0 and handled by the generated container decoder, so it
    # no longer needs an override.
    #
    # OPEN_CATALOG_URLS keeps a one-line override only for its default: legacy
    # get_delimited_list(default="") yields [""], but 0.9.0's generated decoder
    # maps an empty string to []. NoDecode + the generated decoder still parse
    # any real env value; this only pins the unset default to match legacy.
    OPEN_CATALOG_URLS: Annotated[list[str], NoDecode] = Field(
        default_factory=lambda: [""],
        validation_alias=AliasChoices("OPEN_CATALOG_URLS"),
        description="Open catalog urls",
    )
    # The two OCW_EXTRA_THEMES_* dicts use main/envs.py get_dict_of_str, which
    # static discovery still emits as `Any` (the decoders don't target them);
    # declare them typed with NoDecode + the literal parser below.
    OCW_EXTRA_THEMES_BASE_URLS: Annotated[dict[str, str], NoDecode] = Field(
        default_factory=dict,
        validation_alias=AliasChoices("OCW_EXTRA_THEMES_BASE_URLS"),
        description="Extra Hugo theme slug -> base URL mapping",
    )
    OCW_EXTRA_THEMES_GTM_IDS: Annotated[dict[str, str], NoDecode] = Field(
        default_factory=dict,
        validation_alias=AliasChoices("OCW_EXTRA_THEMES_GTM_IDS"),
        description="Extra Hugo theme slug -> Google Tag Manager ID mapping",
    )
    # Derived/composite settings typed to their final shape; the derive
    # validator below rebuilds them from their primitive inputs.
    ADMINS: tuple[tuple[str, str], ...] = ()
    ANYMAIL: dict[str, Any] = Field(default_factory=dict)
    BASE_DIR: str = Field(
        default_factory=lambda: str(Path(__file__).resolve().parent.parent)
    )
    CACHES: dict[str, Any] = Field(default_factory=dict)
    CELERY_BEAT_SCHEDULE: dict[str, Any] = Field(default_factory=dict)
    DATABASES: dict[str, Any] = Field(default_factory=dict)
    DEFAULT_DATABASE_CONFIG: dict[str, Any] = Field(default_factory=dict)
    LOGGING: dict[str, Any] = Field(default_factory=dict)
    SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: list[str] = Field(default_factory=list)
    STATICFILES_DIRS: tuple[str, ...] = ()
    STORAGES: dict[str, Any] = Field(
        default_factory=lambda: dict(_DJANGO_DEFAULT_STORAGES)
    )
    TEMPLATES: list[dict[str, Any]] = Field(default_factory=list)
    WEBPACK_LOADER: dict[str, Any] = Field(default_factory=dict)

    # ------------------------------------------------------------------
    # Field validators
    # ------------------------------------------------------------------

    @field_validator(
        "OCW_EXTRA_THEMES_BASE_URLS",
        "OCW_EXTRA_THEMES_GTM_IDS",
        mode="before",
    )
    @classmethod
    def _parse_literal(cls, value: Any) -> Any:
        """Parse Python-literal env values, mirroring main/envs.py helpers."""
        if isinstance(value, str):
            return literal_eval(value)
        return value

    # ------------------------------------------------------------------
    # Cross-field validation ported from main/settings.py
    # ------------------------------------------------------------------

    @model_validator(mode="after")
    def _validate_playwright_image_arch(self) -> AqueductSettings:
        """Reject any PLAYWRIGHT_IMAGE_ARCH other than "" or "amd64"."""
        if self.PLAYWRIGHT_IMAGE_ARCH not in {"", "amd64"}:
            msg = (
                "PLAYWRIGHT_IMAGE_ARCH must be 'amd64' or unset, "
                f"got {self.PLAYWRIGHT_IMAGE_ARCH!r}"
            )
            raise ImproperlyConfigured(msg)
        return self

    @model_validator(mode="after")
    def _validate_s3_credentials(self) -> AqueductSettings:
        """Require complete S3 credentials whenever OCW_STUDIO_USE_S3 is set."""
        if self.OCW_STUDIO_USE_S3 and (
            not self.AWS_ACCESS_KEY_ID
            or not self.AWS_SECRET_ACCESS_KEY
            or not self.AWS_STORAGE_BUCKET_NAME
        ):
            msg = (
                "You have enabled S3 support, but are missing one of "
                "AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, or AWS_STORAGE_BUCKET_NAME"
            )
            raise ImproperlyConfigured(msg)
        return self

    @model_validator(mode="after")
    def _validate_extra_theme_gtm_ids(self) -> AqueductSettings:
        """Reject GTM ids for themes not in OCW_EXTRA_COURSE_THEMES."""
        unknown = set(self.OCW_EXTRA_THEMES_GTM_IDS) - set(self.OCW_EXTRA_COURSE_THEMES)
        if unknown:
            msg = (
                "OCW_EXTRA_THEMES_GTM_IDS contains theme slugs that are not "
                f"configured in OCW_EXTRA_COURSE_THEMES: {', '.join(sorted(unknown))}"
            )
            raise ImproperlyConfigured(msg)
        return self

    # ------------------------------------------------------------------
    # Derivations (single validator so evaluation order is explicit)
    # ------------------------------------------------------------------

    @model_validator(mode="after")
    def _derive_settings(self) -> AqueductSettings:
        """Rebuild every composite setting from its primitive inputs.

        Mirrors main/settings.py's derivation order exactly, using the shared
        helpers in django_aqueduct.derivations where they match.
        """
        # mitol.mail.settings.email fallback chain
        if self.EMAIL_RECIPIENT_OVERRIDE is None:
            self.EMAIL_RECIPIENT_OVERRIDE = self.MAILGUN_RECIPIENT_OVERRIDE
        if self.EMAIL_SUPPORT is None:
            self.EMAIL_SUPPORT = self.EMAIL_RECIPIENT_OVERRIDE or "support@localhost"
        if self.MITOL_MAIL_ENABLE_EMAIL_DEBUGGER is None:
            self.MITOL_MAIL_ENABLE_EMAIL_DEBUGGER = self.DEBUG

        # GITHUB_APP_PRIVATE_KEY unicode-escape roundtrip (idempotent: skip
        # values that are already bytes so re-validation cannot crash).
        if isinstance(self.GITHUB_APP_PRIVATE_KEY, str):
            self.GITHUB_APP_PRIVATE_KEY = (
                self.GITHUB_APP_PRIVATE_KEY.encode().decode("unicode_escape").encode()
            )

        # Databases
        config = dv.database_config(
            self.DATABASE_URL,
            conn_max_age=self.OCW_STUDIO_DB_CONN_MAX_AGE,
            ssl_require=not self.OCW_STUDIO_DB_DISABLE_SSL,
        )
        config["DISABLE_SERVER_SIDE_CURSORS"] = self.OCW_STUDIO_DB_DISABLE_SS_CURSORS
        config.setdefault("OPTIONS", {})
        self.DEFAULT_DATABASE_CONFIG = config
        self.DATABASES = {"default": config}

        # Celery broker/result fall back to RedisCloud, then plain Redis.
        redis_url = dv.first_url(self.REDISCLOUD_URL, self.REDIS_URL)
        if self.CELERY_BROKER_URL is None:
            self.CELERY_BROKER_URL = redis_url
        if self.CELERY_RESULT_BACKEND is None:
            self.CELERY_RESULT_BACKEND = redis_url

        # Caches (redis LOCATION follows the resolved broker URL)
        self.CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            "redis": dv.redis_cache(
                self.CELERY_BROKER_URL,
                CLIENT_CLASS="django_redis.client.DefaultClient",
                CONNECTION_POOL_KWARGS={"max_connections": self.REDIS_MAX_CONNECTIONS},
            ),
        }

        # Conditional apps/middleware, appended to the generated base lists in
        # the same order as main/settings.py.
        installed_apps = list(self.INSTALLED_APPS)
        middleware: list[Any] = list(self.MIDDLEWARE)
        if self.ENVIRONMENT not in PRODUCTION_NAMES:
            installed_apps.append("localdev")
        if not self.DISABLE_WEBPACK_LOADER_STATS:
            installed_apps.append("webpack_loader")
        if self.DEBUG:
            installed_apps.append("nplusone.ext.django")
            middleware.append("nplusone.ext.django.NPlusOneMiddleware")
        if self.MIDDLEWARE_FEATURE_FLAG_QS_PREFIX:
            # NOTE: main/settings.py appends a *list* here rather than
            # extending (pre-existing bug in the original module); preserved
            # as-is for parity.
            middleware.append(
                [
                    "main.middleware.QueryStringFeatureFlagMiddleware",
                    "main.middleware.CookieFeatureFlagMiddleware",
                ]
            )
        if self.DEBUG:
            installed_apps.append("debug_toolbar")
            middleware.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
        self.INSTALLED_APPS = installed_apps
        self.MIDDLEWARE = middleware

        # Celery beat schedule from the *_FREQUENCY fields
        schedule: dict[str, Any] = {
            "update-youtube-statuses": {
                "task": "videos.tasks.update_youtube_statuses",
                "schedule": self.YT_STATUS_UPDATE_FREQUENCY,
            },
            "upload-youtube-videos": {
                "task": "videos.tasks.upload_youtube_videos",
                "schedule": self.YT_UPLOAD_FREQUENCY,
            },
            "update-transcripts-for-updated-videos": {
                "task": "videos.tasks.update_transcripts_for_updated_videos",
                "schedule": self.UPDATE_TAGGED_3PLAY_TRANSCRIPT_FREQUENCY,
            },
            "attempt-to-update-missing-transcripts": {
                "task": "videos.tasks.attempt_to_update_missing_transcripts",
                "schedule": self.UPDATE_MISSING_TRANSCRIPT_FREQUENCY,
            },
            "check_incomplete_publish_build_statuses": {
                "task": "content_sync.tasks.check_incomplete_publish_build_statuses",
                "schedule": self.PUBLISH_INCOMPLETE_BUILD_STATUS_FREQUENCY,
            },
        }
        if self.ENABLE_WAYBACK_TASKS:
            schedule["update-wayback-jobs-status"] = {
                "task": "external_resources.tasks.update_wayback_jobs_status_batch",
                "schedule": self.UPDATE_WAYBACK_JOBS_STATUS_FREQUENCY,
            }
        if self.ENABLE_CHECK_EXTERNAL_RESOURCE_TASK:
            schedule["check-broken-external-urls"] = {
                "task": "external_resources.tasks.check_external_resources_for_breakages",
                "schedule": self.CHECK_EXTERNAL_RESOURCE_STATUS_FREQUENCY,
            }
        self.CELERY_BEAT_SCHEDULE = schedule

        # Logging driven by the LOG_* fields and this host's name (the legacy
        # module builds the same dict at import time).
        self.LOGGING = {
            "version": 1,
            "disable_existing_loggers": False,
            "filters": {
                "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"}
            },
            "formatters": {
                "verbose": {
                    "format": (
                        "[%(asctime)s] %(levelname)s %(process)d [%(name)s] "
                        "%(filename)s:%(lineno)d - "
                        f"[{self.HOSTNAME}] - %(message)s"
                    ),
                    "datefmt": "%Y-%m-%d %H:%M:%S",
                }
            },
            "handlers": {
                "console": {
                    "level": "DEBUG",
                    "class": "logging.StreamHandler",
                    "formatter": "verbose",
                },
                "syslog": {
                    "level": self.LOG_LEVEL,
                    "class": "logging.handlers.SysLogHandler",
                    "facility": "local7",
                    "formatter": "verbose",
                    "address": (self.LOG_HOST, self.LOG_HOST_PORT),
                },
                "mail_admins": {
                    "level": "ERROR",
                    "filters": ["require_debug_false"],
                    "class": "django.utils.log.AdminEmailHandler",
                },
            },
            "loggers": {
                "django": {
                    "propagate": True,
                    "level": self.DJANGO_LOG_LEVEL,
                    "handlers": ["console", "syslog"],
                },
                "django.request": {
                    "handlers": ["mail_admins"],
                    "level": self.DJANGO_LOG_LEVEL,
                    "propagate": True,
                },
                "nplusone": {"handlers": ["console"], "level": "ERROR"},
            },
            "root": {
                "handlers": ["console", "syslog"],
                "level": self.LOG_LEVEL,
            },
        }

        # Remaining simple derivations
        self.ADMINS = (("Admins", self.ADMIN_EMAIL),) if self.ADMIN_EMAIL else ()
        self.INTERNAL_IPS = (self.HOST_IP,)
        self.SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS = [urlparse(self.SITE_BASE_URL).netloc]
        self.ANYMAIL = {
            "MAILGUN_API_KEY": self.MAILGUN_KEY,
            "MAILGUN_SENDER_DOMAIN": self.MAILGUN_SENDER_DOMAIN,
        }
        self.STATICFILES_DIRS = (os.path.join(self.BASE_DIR, "static"),)
        self.TEMPLATES = [
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "DIRS": [f"{self.BASE_DIR}/templates"],
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.debug",
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                    ],
                },
            },
        ]
        self.WEBPACK_LOADER = {
            "DEFAULT": {
                "CACHE": not self.DEBUG,
                "BUNDLE_DIR_NAME": "bundles/",
                "STATS_FILE": os.path.join(self.BASE_DIR, "webpack-stats.json"),
                "POLL_INTERVAL": 0.1,
                "TIMEOUT": None,
                "IGNORE": [r".+\.hot-update\.+", r".+\.js\.map"],
            }
        }
        if self.OCW_STUDIO_USE_S3:
            self.STORAGES = {
                "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
                "staticfiles": {
                    "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
                },
            }

        # Feature flags: FEATURE_* environment variables (the layer pydantic
        # cannot surface for undeclared names) merged with FEATURE_* keys
        # arriving through the settings sources (e.g. Vault), read via the
        # shared derivation so source-supplied flags are never missed.
        flags: dict[str, Any] = {
            key[len("FEATURE_") :]: value
            for key, value in os.environ.items()
            if key.startswith("FEATURE_")
        }
        flags.update(dv.feature_flags(self.model_extra or {}))
        self.FEATURES = {
            name: _feature_bool(name, value) for name, value in flags.items()
        }

        return self
    # <<< aqueduct:preserved:validators


def init_sentry_from_model(model: AqueductSettings) -> None:
    """``pre_configure`` hook: initialise Sentry from the validated model.

    Runs before the model's values are injected into Django settings, matching
    main/settings.py's "initialize Sentry before doing anything else" order.
    """
    from main.sentry import init_sentry

    init_sentry(
        dsn=model.SENTRY_DSN,
        environment=model.ENVIRONMENT,
        version=model.VERSION,
        log_level=model.SENTRY_LOG_LEVEL,
        heroku_app_name=model.HEROKU_APP_NAME,
    )


class DevAqueductSettings(AqueductSettings):
    """Local-dev variant: fills values missing from the environment from Vault.

    The Vault source is configured entirely from ``VAULT_*`` environment
    variables via :func:`django_aqueduct.sources.dev.vault_source_from_env`
    (``VAULT_ADDR``, ``VAULT_PATH``, ``VAULT_MOUNT``, ``VAULT_AUTH_METHOD``,
    ``VAULT_ROLE``, ...). When ``VAULT_ADDR`` is unset the source is skipped
    and this behaves exactly like :class:`AqueductSettings`; when Vault is
    enabled but misconfigured, a descriptive ``VaultConfigError`` is raised
    instead of a bare ``KeyError``.

    Vault is appended *after* the standard sources so explicit environment
    variables always win over Vault-supplied values.
    """

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,
        file_secret_settings,
    ):
        """Append an env-configured Vault source below env/.env sources."""
        base = (init_settings, env_settings, dotenv_settings, file_secret_settings)
        vault = vault_source_from_env(settings_cls)
        return (*base, vault) if vault is not None else base
