"""Typed Aqueduct settings model for ocw-studio.

Generated by ``manage.py generate_aqueduct_settings`` and then hand-refined:

* Field descriptions/required-ness were reconciled between the plain module
  scan of ``main.settings`` and the mitol ``EnvParser`` registry scan
  (``--include-envparser``). Where the Django-setting attribute name differs
  from the real environment variable name (e.g. ``SITE_ID`` is populated from
  ``OCW_STUDIO_SITE_ID``), the field keeps the Django name and uses
  ``validation_alias`` to point at the real env var.
* Settings pulled into ``main.settings`` via
  ``import_settings_modules("mitol.common.settings.base", ...)`` (e.g.
  ``SITE_BASE_URL``) are included as ordinary fields.
* The three settings in ``main/envs.py`` (``OCW_TEST_SITE_SLUGS``,
  ``OCW_EXTRA_THEMES_BASE_URLS``, ``OCW_EXTRA_THEMES_GTM_IDS``) bypass the
  mitol ``EnvParser`` registry entirely, so they are declared by hand below.
* Derived/composite settings (``DATABASES``, ``INSTALLED_APPS``,
  ``MIDDLEWARE``, ``CACHES``, ``CELERY_BEAT_SCHEDULE``, etc.) and the
  cross-field validations that exist in ``main/settings.py`` today are
  reproduced with ``@model_validator`` methods below, preserving the exact
  runtime behavior of the original settings module.

This module is purely additive: ``main/settings.py`` and ``main/envs.py`` are
untouched and remain the default settings used everywhere until a settings
module built on top of this model is explicitly selected via
``DJANGO_SETTINGS_MODULE``.
"""

from __future__ import annotations

import os
import pathlib
from typing import Any
from urllib.parse import urlparse

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from pydantic import Field, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

from main.constants import PRODUCTION_NAMES


def _scan_feature_flags(prefix: str = "FEATURE_") -> dict[str, bool]:
    """Scan ``os.environ`` for ``FEATURE_``-prefixed variables.

    Mirrors ``mitol.common.envs.EnvParser.get_features()``: every environment
    variable starting with *prefix* becomes a feature flag, keyed by the
    remainder of its name with the prefix stripped, parsed as a boolean.

    Args:
        prefix: The environment variable prefix that marks a feature flag.

    Returns:
        A dict of feature name to boolean value.

    Raises:
        ImproperlyConfigured: If a ``FEATURE_*`` variable isn't ``"true"`` or
            ``"false"`` (case-insensitive).
    """
    features: dict[str, bool] = {}
    for key, value in os.environ.items():
        if not key.startswith(prefix):
            continue
        parsed = value.strip().lower()
        if parsed == "true":
            features[key[len(prefix) :]] = True
        elif parsed == "false":
            features[key[len(prefix) :]] = False
        else:
            msg = f"Expected value in {key}={value} to be a boolean"
            raise ImproperlyConfigured(msg)
    return features


class AqueductSettings(BaseSettings):
    """Typed Django settings model for ocw-studio.

    Populate from environment variables, a ``.env`` file, or (via
    :class:`DevAqueductSettings`) Vault. All ``django.conf.settings.FOO``
    access in application code continues to work unchanged once this model
    is wired up through ``main/settings_aqueduct.py``.
    """

    model_config = SettingsConfigDict(
        env_prefix="",
        extra="allow",
    )

    ADMINS: tuple[Any, ...] = Field(
        default=()
    )  # DERIVED: rebuilt in a model_validator from ADMIN_EMAIL
    ADMIN_EMAIL: str = Field(
        default="",
        validation_alias="OCW_STUDIO_ADMIN_EMAIL",
        description="E-mail to send 500 reports to.",
    )
    ALLOWED_HOSTS: list[str] = Field(default_factory=lambda: ["*"])
    ANYMAIL: dict[str, Any] = Field(
        default_factory=dict
    )  # DERIVED: rebuilt in a model_validator from MAILGUN_KEY/MAILGUN_SENDER_DOMAIN
    API_BEARER_TOKEN: Any = Field(
        default=None, description="Authorization bearer token for webhook endpoints"
    )  # TODO: refine type
    APP_SETTINGS_NAMESPACE: str = Field(
        default="OCW_STUDIO", description="App environment variable namespace"
    )
    ARCHIVE_URL_REQUEST_TIMEOUT: int = Field(
        default=120,
        description="Timeout for making HEAD requests to archive_url to fetch file size for videos",  # noqa: E501
    )
    AUTHENTICATION_BACKENDS: tuple[Any, ...] = Field(
        default=(
            "social_core.backends.keycloak.KeycloakOAuth2",
            "django.contrib.auth.backends.ModelBackend",
            "guardian.backends.ObjectPermissionBackend",
        )
    )  # TODO: refine type
    AUTH_USER_MODEL: str = Field(default="users.User")
    AWS_ACCESS_KEY_ID: Any = Field(
        default=None, description="AWS Access Key for S3 storage."
    )  # TODO: refine type
    AWS_ACCOUNT_ID: Any = Field(
        default=None, description="AWS Account ID"
    )  # TODO: refine type
    AWS_ARTIFACTS_BUCKET_NAME: Any = Field(
        default=None, description="S3 artifacts bucket name."
    )  # TODO: refine type
    AWS_DEFAULT_ACL: str = Field(default="public-read")
    AWS_IMPORT_STORAGE_BUCKET_NAME: Any = Field(
        default=None, description="S3 bucket name to import/sync storage from."
    )  # TODO: refine type
    AWS_MAX_CONCURRENT_CONNECTIONS: int = Field(
        default=10,
        description="The max concurrent connections used by cp and sync AWS CLI commands",  # noqa: E501
    )
    AWS_OFFLINE_PREVIEW_BUCKET_NAME: Any = Field(
        default=None, description="S3 offline preview bucket name."
    )  # TODO: refine type
    AWS_OFFLINE_PUBLISH_BUCKET_NAME: Any = Field(
        default=None, description="S3 offline publish bucket name."
    )  # TODO: refine type
    AWS_OFFLINE_TEST_BUCKET_NAME: Any = Field(
        default=None, description="S3 offline test bucket name."
    )  # TODO: refine type
    AWS_PREVIEW_BUCKET_NAME: Any = Field(
        default=None, description="S3 preview bucket name."
    )  # TODO: refine type
    AWS_PUBLISH_BUCKET_NAME: Any = Field(
        default=None, description="S3 publish bucket name."
    )  # TODO: refine type
    AWS_QUERYSTRING_AUTH: bool = Field(
        default=False, description="Enables querystring auth for S3 urls"
    )
    AWS_REGION: str = Field(default="us-east-1", description="AWS Region")
    AWS_ROLE_NAME: Any = Field(
        default=None, description="AWS role name to be used for MediaConvert jobs"
    )  # TODO: refine type
    AWS_S3_SYNC_INTERVAL: str = Field(
        default="24h",
        description="Interval for S3 bucket sync pipeline (e.g., '24h', '12h', '6h').",
    )
    AWS_SECRET_ACCESS_KEY: Any = Field(
        default=None, description="AWS Secret Key for S3 storage."
    )  # TODO: refine type
    AWS_STORAGE_BUCKET_NAME: Any = Field(
        default=None, description="S3 Bucket name."
    )  # TODO: refine type
    AWS_TEST_BUCKET_NAME: Any = Field(
        default=None, description="S3 test bucket name."
    )  # TODO: refine type
    BASE_DIR: str = Field(
        default_factory=lambda: str(pathlib.Path(__file__).resolve().parent.parent)
    )
    CACHES: dict[str, Any] = Field(
        default_factory=lambda: {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            "redis": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": None,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    "CONNECTION_POOL_KWARGS": {"max_connections": 48},
                },
            },
        }
    )  # DERIVED: redis LOCATION/max_connections rebuilt in a model_validator
    CELERY_ACCEPT_CONTENT: list[str] = Field(default_factory=lambda: ["json"])
    CELERY_BEAT_SCHEDULE: dict[str, Any] = Field(
        default_factory=dict
    )  # DERIVED: rebuilt in a model_validator from the *_FREQUENCY fields
    CELERY_BROKER_URL: str | None = Field(
        default=None, description="Where celery should get tasks, default is Redis URL"
    )  # DERIVED: falls back to REDISCLOUD_URL/REDIS_URL in a model_validator
    CELERY_RESULT_BACKEND: str | None = Field(
        default=None,
        description="Where celery should put task results, default is Redis URL",
    )  # DERIVED: falls back to REDISCLOUD_URL/REDIS_URL in a model_validator
    CELERY_RESULT_SERIALIZER: str = Field(default="json")
    CELERY_TASK_ALWAYS_EAGER: bool = Field(
        default=False,
        description="Enables eager execution of celery tasks, development only",
    )  # dev-only
    CELERY_TASK_EAGER_PROPAGATES: bool = Field(
        default=True, description="Early executed tasks propagate exceptions"
    )
    CELERY_TASK_SERIALIZER: str = Field(default="json")
    CELERY_TIMEZONE: str = Field(default="UTC")
    CHECK_EXTERNAL_RESOURCE_STATUS_FREQUENCY: int = Field(
        default=604800,
        description="Frequency (in seconds) to check potentially broken external urls",
    )
    CONCOURSE_HARD_PURGE: bool = Field(
        default=True, description="Perform a hard purge of the fastly cache"
    )
    CONCOURSE_IS_PRIVATE_REPO: bool = Field(
        default=True,
        description="True if a git repo requires authentication to retrieve",
    )
    CONCOURSE_PASSWORD: Any = Field(
        default=None, description="The concourse-ci login password"
    )  # TODO: refine type
    CONCOURSE_TEAM: str = Field(default="ocw", description="The concourse-ci team")
    CONCOURSE_URL: Any = Field(
        default=None, description="The concourse-ci URL"
    )  # TODO: refine type
    CONCOURSE_USERNAME: Any = Field(
        default=None, description="The concourse-ci login username"
    )  # TODO: refine type
    CONTENT_FILE_SEARCH_API_URL: Any = Field(
        default=None,
        description="The URL to open discussions content file search to inject into the theme assets build",  # noqa: E501
    )  # TODO: refine type
    CONTENT_SYNC_BACKEND: Any = Field(
        default=None, description="The backend to sync websites/content with"
    )  # TODO: refine type
    CONTENT_SYNC_PIPELINE_BACKEND: str = Field(
        default="concourse",
        description="The pipeline backend name to preview/publish websites with",
    )
    CONTENT_SYNC_RETRIES: int = Field(
        default=5, description="Number of times to retry backend sync attempts"
    )
    COURSE_SEARCH_API_URL: Any = Field(
        default=None,
        description="The URL to open discussions learning resource search to inject into the theme assets build",  # noqa: E501
    )  # TODO: refine type
    DATABASES: dict[str, Any] = Field(
        default_factory=dict
    )  # DERIVED: rebuilt in a model_validator from DATABASE_URL
    DATABASE_URL: str = Field(
        default_factory=lambda: (
            f"sqlite:///{pathlib.Path(__file__).resolve().parent.parent / 'db.sqlite3'}"
        ),
        description="The connection url to the Postgres database",
    )
    DEBUG: bool = Field(
        default=False,
        description="Set to True to enable DEBUG mode. Don't turn on in production.",
    )  # dev-only
    DEFAULT_AUTO_FIELD: str = Field(default="django.db.models.AutoField")
    DEFAULT_DATABASE_CONFIG: dict[str, Any] = Field(
        default_factory=dict
    )  # DERIVED: rebuilt in a model_validator from DATABASE_URL
    DEFAULT_FROM_EMAIL: str = Field(
        default="webmaster@localhost",
        validation_alias="OCW_STUDIO_FROM_EMAIL",
        description="E-mail to use for the from field",
    )
    DISABLE_WEBPACK_LOADER_STATS: bool = Field(
        default=False, description="Disabled webpack loader stats"
    )
    DJANGO_LOG_LEVEL: str = Field(
        default="INFO", description="The log level for django"
    )
    DJANGO_REDIS_CLOSE_CONNECTION: bool = Field(default=True)
    DRIVE_S3_UPLOAD_PREFIX: str = Field(
        default="gdrive_uploads",
        description="Prefix to be used for S3 keys of files uploaded from Google Drive",
    )
    DRIVE_SERVICE_ACCOUNT_CREDS: Any = Field(
        default=None,
        description="The contents of the Service Account credentials JSON to use for Google API auth",  # noqa: E501
    )  # TODO: refine type
    DRIVE_SHARED_ID: Any = Field(
        default=None,
        description="ID of the Shared Drive (a.k.a. Team Drive). This is equal to the top-level folder ID.",  # noqa: E501
    )  # TODO: refine type
    DRIVE_UPLOADS_PARENT_FOLDER_ID: Any = Field(
        default=None, description="Gdrive folder for video uploads"
    )  # TODO: refine type
    EMAIL_BACKEND: str = Field(
        default="django.core.mail.backends.smtp.EmailBackend",
        validation_alias="OCW_STUDIO_EMAIL_BACKEND",
        description="The default email backend to use for outgoing email. This is used in some places by django itself. See `NOTIFICATION_EMAIL_BACKEND` for the backend used for most application emails.",  # noqa: E501
    )
    EMAIL_HOST: str = Field(
        default="localhost",
        validation_alias="OCW_STUDIO_EMAIL_HOST",
        description="Outgoing e-mail hostname",
    )
    EMAIL_HOST_PASSWORD: str = Field(
        default="",
        validation_alias="OCW_STUDIO_EMAIL_PASSWORD",
        description="Outgoing e-mail auth password",
    )
    EMAIL_HOST_USER: str = Field(
        default="",
        validation_alias="OCW_STUDIO_EMAIL_USER",
        description="Outgoing e-mail auth username",
    )
    EMAIL_PORT: int = Field(
        default=25,
        validation_alias="OCW_STUDIO_EMAIL_PORT",
        description="Outgoing e-mail port",
    )
    EMAIL_RECIPIENT_OVERRIDE: Any = Field(
        default=None,
        description="Override the recipient for outgoing email, development only",
    )  # TODO: refine type  # dev-only
    EMAIL_SUPPORT: str = Field(
        default="support@localhost",
        validation_alias="OCW_STUDIO_SUPPORT_EMAIL",
        description="Email address listed for customer support",
    )
    EMAIL_USE_TLS: bool = Field(
        default=False,
        validation_alias="OCW_STUDIO_EMAIL_TLS",
        description="Outgoing e-mail TLS setting",
    )
    ENABLE_CHECK_EXTERNAL_RESOURCE_TASK: bool = Field(
        default=True,
        validation_alias="CHECK_EXTERNAL_RESOURCE_TASK_STATUS",
        description="Enables celery task to check potentially broken external urls",
    )
    ENABLE_WAYBACK_TASKS: bool = Field(
        default=False,
        description="Enables tasks related to Wayback Machine submissions and status checks",  # noqa: E501
    )
    ENV_NAME: str = Field(
        default="rc", description="Name of environment from Heroku or other deployment"
    )
    FEATURES_DEFAULT: bool = Field(
        default=False, description="The default value for all feature flags"
    )  # dev-only
    FIELD_METADATA_TITLE: str = Field(
        default="course_title", description="The site metadata field for title"
    )
    FIELD_RESOURCETYPE: str = Field(
        default="resourcetype",
        description="The site config metadata field for the resource type",
    )
    GA_TRACKING_ID: str = Field(default="", description="Google analytics tracking ID")
    GITHUB_APP_ID: Any = Field(
        default=None, description="A github app id to use for Github API authentication"
    )  # TODO: refine type
    GITHUB_RATE_LIMIT_CHECK: bool = Field(
        default=False, description="True if the github domain has API rate limits"
    )
    GITHUB_RATE_LIMIT_CUTOFF: int = Field(
        default=100,
        description="Number of remaining Github API calls that triggers throttling",
    )
    GITHUB_RATE_LIMIT_MIN_SLEEP: int = Field(
        default=5,
        description="Minimum time to sleep between when throttling github calls",
    )
    GITHUB_TIMEOUT: int = Field(
        default=15, description="Timeout in seconds for Github API requests"
    )
    GITHUB_WEBHOOK_BRANCH: str = Field(
        default="", description="Github branch to filter webhook requests against"
    )
    GITHUB_WEBHOOK_KEY: str = Field(
        default="", description="Github secret key sent by webhook requests"
    )
    GIT_API_URL: Any = Field(
        default=None, description="Base URL of git API"
    )  # TODO: refine type
    GIT_BRANCH_MAIN: str = Field(
        default="main", description="The default branch for a git repo"
    )
    GIT_BRANCH_PREVIEW: str = Field(
        default="preview", description="The preview branch for a git repo"
    )
    GIT_BRANCH_RELEASE: str = Field(
        default="release", description="The release branch for a git repo"
    )
    GIT_DEFAULT_USER_EMAIL: str = Field(
        default="anonymous@example.edu",
        description="The email for the default git committer",
    )
    GIT_DEFAULT_USER_NAME: str = Field(
        default="Anonymous", description="The name for the default git committer"
    )
    GIT_DOMAIN: str = Field(
        default="www.github.com", description="Base URL of github for site repos"
    )
    GIT_ORGANIZATION: Any = Field(
        default=None, description="The organization under which repos should be created"
    )  # TODO: refine type
    GIT_TOKEN: Any = Field(
        default=None, description="An authentication token for git commands"
    )  # TODO: refine type
    HEALTH_CHECK: list[str] = Field(
        default_factory=lambda: ["CELERY", "REDIS", "POSTGRES"]
    )
    HEROKU_APP_NAME: Any = Field(
        default=None, description="The name of the review app"
    )  # TODO: refine type
    HIJACK_ALLOW_GET_REQUESTS: bool = Field(default=True)
    HIJACK_LOGIN_REDIRECT_URL: str = Field(default="sites")
    HIJACK_LOGOUT_REDIRECT_URL: str = Field(default="/admin/users/user/")
    HIJACK_REGISTER_ADMIN: bool = Field(default=False)
    HOSTNAME: str = Field(default="ikoria")
    HOST_IP: str = Field(default="127.0.0.1", description="This server's host IP")
    INSTALLED_APPS: list[str] = Field(
        default_factory=list
    )  # DERIVED: rebuilt in a model_validator based on ENVIRONMENT/DISABLE_WEBPACK_LOADER_STATS/DEBUG  # noqa: E501
    INTERNAL_IPS: tuple[Any, ...] = Field(
        default=()
    )  # DERIVED: rebuilt in a model_validator from HOST_IP
    LANGUAGE_CODE: str = Field(default="en-us")
    LOGGING: dict[str, Any] = Field(
        default_factory=lambda: {
            "version": 1,
            "disable_existing_loggers": False,
            "filters": {
                "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"}
            },
            "formatters": {
                "verbose": {
                    "format": "[%(asctime)s] %(levelname)s %(process)d [%(name)s] %(filename)s:%(lineno)d - [ikoria] - %(message)s",  # noqa: E501
                    "datefmt": "%Y-%m-%d %H:%M:%S",
                }
            },
            "handlers": {
                "console": {
                    "level": "DEBUG",
                    "class": "logging.StreamHandler",
                    "formatter": "verbose",
                },
                "syslog": {
                    "level": "INFO",
                    "class": "logging.handlers.SysLogHandler",
                    "facility": "local7",
                    "formatter": "verbose",
                    "address": ("localhost", 514),
                },
                "mail_admins": {
                    "level": "ERROR",
                    "filters": ["require_debug_false"],
                    "class": "django.utils.log.AdminEmailHandler",
                },
            },
            "loggers": {
                "django": {
                    "propagate": True,
                    "level": "INFO",
                    "handlers": ["console", "syslog"],
                },
                "django.request": {
                    "handlers": ["mail_admins"],
                    "level": "INFO",
                    "propagate": True,
                },
                "nplusone": {"handlers": ["console"], "level": "ERROR"},
            },
            "root": {"handlers": ["console", "syslog"], "level": "INFO"},
        }
    )
    LOGIN_ERROR_URL: str = Field(default="/")
    LOGIN_REDIRECT_URL: str = Field(default="/")
    LOGIN_URL: str = Field(default="/")
    LOGOUT_REDIRECT_URL: str = Field(default="/")
    LOG_HOST: str = Field(
        default="localhost",
        validation_alias="OCW_STUDIO_LOG_HOST",
        description="Remote syslog server hostname",
    )
    LOG_HOST_PORT: int = Field(
        default=514,
        validation_alias="OCW_STUDIO_LOG_HOST_PORT",
        description="Remote syslog server port",
    )
    LOG_LEVEL: str = Field(
        default="INFO",
        validation_alias="OCW_STUDIO_LOG_LEVEL",
        description="The log level default",
    )
    MAILGUN_RECIPIENT_OVERRIDE: Any = Field(
        default=None,
        description="Override the recipient for outgoing email, development only",
    )  # TODO: refine type  # dev-only
    MAX_S3_GET_ITERATIONS: int = Field(
        default=3, description="Max retry attempts to get an S3 object"
    )
    MEDIA_ROOT: str = Field(
        default="/var/media/",
        description="The root directory for locally stored media. Typically not used.",
    )
    MEDIA_URL: str = Field(default="/media/")
    MIDDLEWARE: list[str] = Field(
        default_factory=list
    )  # DERIVED: rebuilt in a model_validator based on DEBUG/MIDDLEWARE_FEATURE_FLAG_QS_PREFIX  # noqa: E501
    MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS: int = Field(
        default=3600, description="Feature flag middleware cookie max age"
    )
    MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME: str = Field(
        default="OCW_STUDIO_FEATURE_FLAGS",
        description="Feature flag middleware cookie name",
    )
    MIDDLEWARE_FEATURE_FLAG_QS_PREFIX: Any = Field(
        default=None, description="Feature flag middleware querystring prefix"
    )  # TODO: refine type
    MITOL_MAIL_ENABLE_EMAIL_DEBUGGER: bool = Field(
        default=False, description="Enable the mitol-mail email debugger"
    )  # dev-only
    MITOL_MAIL_FORMAT_RECIPIENT_FUNC: str = Field(
        default="users.utils.format_recipient",
        description="function to format email recipients",
    )
    MITOL_MAIL_FROM_EMAIL: str = Field(
        default="webmaster@localhost", description="E-mail to use for the from field"
    )
    MITOL_MAIL_MESSAGE_CLASSES: list[str] = Field(
        default_factory=lambda: [
            "videos.messages.YouTubeUploadSuccessMessage",
            "videos.messages.YouTubeUploadFailureMessage",
            "websites.messages.PreviewOrPublishSuccessMessage",
            "websites.messages.PreviewOrPublishFailureMessage",
            "websites.messages.videoTranscriptingCompleteMessage",
        ]
    )
    MITOL_MAIL_RECIPIENT_OVERRIDE: Any = Field(
        default=None,
        description="Override the recipient for outgoing email, development only",
    )  # TODO: refine type  # dev-only
    MITOL_MAIL_REPLY_TO_ADDRESS: str = Field(
        default="webmaster@localhost",
        description="E-mail to use for reply-to address of emails",
    )
    MIT_LEARN_API_BASE_URL: Any = Field(
        default=None, description="URL to an instance of the MIT Learn API"
    )  # TODO: refine type
    MIT_LEARN_BASE_URL: Any = Field(
        default=None, description="URL to an instance of MIT Learn"
    )  # TODO: refine type
    NPLUSONE_LOGGER: Any = Field(
        default=None
    )  # OPAQUE: original Logger value is not serialisable
    NPLUSONE_LOG_LEVEL: int = Field(default=40)
    OCW_COURSE_STARTER_SLUG: str = Field(
        default="course",
        description="The slug of the WebsiteStarter currently used for OCW course sites",  # noqa: E501
    )
    OCW_DEFAULT_COURSE_THEME: str = Field(
        default="ocw-course-v2",
        description="The default Hugo theme to use for OCW course sites",
    )
    OCW_EXTRA_COURSE_THEMES: list[str] = Field(
        default_factory=list,
        description="Additional Hugo themes to build for OCW course sites",
    )
    OCW_GTM_ACCOUNT_ID: Any = Field(
        default=None,
        description="The Google Tag Manager account ID to use in OCW site build pipelines",  # noqa: E501
    )  # TODO: refine type
    OCW_HUGO_PROJECTS_BRANCH: Any = Field(
        default=None,
        description="The branch to use in development of ocw-hugo-projects",
    )  # TODO: refine type  # dev-only
    OCW_HUGO_THEMES_BRANCH: Any = Field(
        default=None, description="The branch to use in development of ocw-hugo-themes"
    )  # TODO: refine type  # dev-only
    OCW_HUGO_THEMES_SENTRY_DSN: Any = Field(
        default=None, description="The sentry DSN that will be used in ocw-hugo-themes"
    )  # TODO: refine type
    OCW_IMPORT_STARTER_SLUG: str = Field(
        default="course",
        description="The slug of the WebsiteStarter to assign to courses imported from ocw-to-hugo",  # noqa: E501
    )
    OCW_MASS_BUILD_BATCH_SIZE: int = Field(
        default=20,
        description="The amount of site builds per job to put in MassBuildSitesPipelineDefinition",  # noqa: E501
    )
    OCW_MASS_BUILD_MAX_IN_FLIGHT: int = Field(
        default=10,
        description="The amount of sites to build simultaneously in each job created by MassBuildSitesPipelineDefinition",  # noqa: E501
    )
    OCW_STUDIO_DB_CONN_MAX_AGE: int = Field(
        default=0, description="Maximum age of connection to Postgres in seconds"
    )
    OCW_STUDIO_DB_DISABLE_SSL: bool = Field(
        default=False, description="Disables SSL to postgres if set to True"
    )
    OCW_STUDIO_DB_DISABLE_SS_CURSORS: bool = Field(
        default=True, description="Disables Postgres server side cursors"
    )
    OCW_STUDIO_DELETABLE_CONTENT_TYPES: list[str] = Field(
        default_factory=list, description="List of content types that can be deleted"
    )
    OCW_STUDIO_DRAFT_URL: Any = Field(
        default=None, description="The base url of the preview site"
    )  # TODO: refine type
    OCW_STUDIO_LIVE_URL: Any = Field(
        default=None, description="The base url of the live site"
    )  # TODO: refine type
    OCW_STUDIO_SITE_CONFIG_FILE: str = Field(
        default="ocw-studio.yaml",
        description="Standard file name for site config files",
    )
    OCW_STUDIO_TEST_URL: Any = Field(
        default=None, description="The base url of the test site"
    )  # TODO: refine type
    OCW_STUDIO_USE_S3: bool = Field(
        default=False, description="Use S3 for storage backend (required on Heroku)"
    )
    OPEN_CATALOG_WEBHOOK_KEY: str = Field(
        default="", description="Open discussions webhook key"
    )
    PLAYWRIGHT_IMAGE_ARCH: str = Field(
        default="",
        description="Architecture suffix for the Playwright image tag (e.g., 'amd64').",
    )
    POSTHOG_API_HOST: str = Field(
        default="https://app.posthog.com", description="API host for PostHog"
    )
    POSTHOG_ENABLED: bool = Field(
        default=False, description="Whether PostHog is enabled"
    )
    POSTHOG_FEATURE_FLAG_REQUEST_TIMEOUT_MS: int = Field(
        default=3000, description="Timeout (ms) for PostHog feature flag requests"
    )
    POSTHOG_MAX_RETRIES: int = Field(
        default=3,
        description="Number of times requests to PostHog are retried if failed",
    )
    POSTHOG_PROJECT_API_KEY: Any = Field(
        default=None, description="API token for communicating with PostHog"
    )  # TODO: refine type
    POST_TRANSCODE_ACTIONS: list[str] = Field(
        default_factory=list, description="Actions to perform before publish"
    )
    PREPUBLISH_ACTIONS: list[str] = Field(
        default_factory=list, description="Actions to perform before publish"
    )
    PRODUCTION_NAMES: set[Any] = Field(
        default_factory=lambda: {"prod", "production"}
    )  # TODO: refine type
    PUBLISH_INCOMPLETE_BUILD_STATUS_FREQUENCY: int = Field(
        default=1800,
        description="Frequency (in seconds) to run a check on potentially stalled publish builds",  # noqa: E501
    )
    PUBLISH_POSTHOG_API_HOST: str = Field(
        default="https://app.posthog.com",
        description="API host for PostHog, published to pipelines",
    )
    PUBLISH_POSTHOG_ENABLED: bool = Field(
        default=False, description="Whether PostHog is enabled, published to pipelines"
    )
    PUBLISH_POSTHOG_FEATURE_FLAG_REQUEST_TIMEOUT_MS: int = Field(
        default=3000,
        description="Timeout (ms) for PostHog feature flag requests, published to pipelines",  # noqa: E501
    )
    PUBLISH_POSTHOG_MAX_RETRIES: int = Field(
        default=3,
        description="Number of times requests to PostHog are retried if failed, published to pipelines",  # noqa: E501
    )
    PUBLISH_POSTHOG_PROJECT_API_KEY: Any = Field(
        default=None,
        description="API token for communicating with PostHog, published to pipelines",
    )  # TODO: refine type
    PUBLISH_STATUS_CUTOFF: int = Field(
        default=1800,
        description="Number of seconds to wait for a publish build to fail/succeed before assuming it's stuck",  # noqa: E501
    )
    PUBLISH_STATUS_WAIT_TIME: int = Field(
        default=600,
        description="Number of seconds to wait for a publish status update before querying for it via api",  # noqa: E501
    )
    REACT_GA_DEBUG: bool = Field(
        default=False, description="Enable debug for react-ga, development only"
    )  # dev-only
    REDISCLOUD_URL: Any = Field(
        default=None, description="RedisCloud connection url"
    )  # TODO: refine type
    REDIS_MAX_CONNECTIONS: int = Field(
        default=48, description="Max number of redis connections"
    )
    REDIS_URL: Any = Field(
        default=None, description="Redis URL for non-production use"
    )  # TODO: refine type
    RESOURCE_BASE_URL_DRAFT: str = Field(
        default="",
        description="The draft resource base url to use when building and deploying sites locally to minio",  # noqa: E501
    )  # dev-only
    RESOURCE_BASE_URL_LIVE: str = Field(
        default="",
        description="The live resource base url to use when building and deploying sites locally to minio",  # noqa: E501
    )  # dev-only
    RESOURCE_TYPE_FIELDS: list[str] = Field(
        default_factory=lambda: ["resourcetype", "filetype"],
        description="List of site configuration fields that are used to store resource type",  # noqa: E501
    )
    REST_FRAMEWORK: dict[str, Any] = Field(
        default_factory=lambda: {
            "DEFAULT_PERMISSION_CLASSES": (
                "rest_framework.permissions.IsAuthenticated",
            ),
            "DEFAULT_AUTHENTICATION_CLASSES": (
                "rest_framework.authentication.SessionAuthentication",
            ),
            "TEST_REQUEST_DEFAULT_FORMAT": "json",
        }
    )
    ROBOTS_CACHE_TIMEOUT: int = Field(
        default=86400, description="How long the robots.txt file should be cached"
    )
    ROBOTS_USE_HOST: bool = Field(default=False)
    ROOT_URLCONF: str = Field(default="main.urls")
    ROOT_WEBSITE_NAME: str = Field(
        default="ocw-www",
        description="The Website name for the site at the root domain",
    )
    S3_TRANSCRIPTS_PREFIX: str = Field(
        default="transcript_files", description="s3 transcripts subfolder"
    )
    SEARCH_API_URL: Any = Field(
        default=None,
        description="The URL to open discussions search to inject into the theme assets build",  # noqa: E501
    )  # TODO: refine type
    SECURE_PROXY_SSL_HEADER: tuple[Any, ...] = Field(
        default=("HTTP_X_FORWARDED_PROTO", "https")
    )  # TODO: refine type
    SECURE_SSL_REDIRECT: bool = Field(
        default=True,
        validation_alias="OCW_STUDIO_SECURE_SSL_REDIRECT",
        description="Application-level SSL redirect setting.",
    )
    SENTRY_DSN: str = Field(
        default="", description="The connection settings for Sentry"
    )
    SENTRY_LOG_LEVEL: str = Field(
        default="ERROR", description="The log level for Sentry"
    )
    SESSION_ENGINE: str = Field(
        default="django.contrib.sessions.backends.signed_cookies"
    )
    SITEMAP_DOMAIN: str = Field(
        default="ocw.mit.edu",
        description="The domain to be used in Hugo builds for fully qualified URLs in the sitemap",  # noqa: E501
    )
    SITE_ID: int = Field(
        default=1,
        validation_alias="OCW_STUDIO_SITE_ID",
        description="The default site id for django sites framework",
    )
    SITE_NAME: str = Field(default="OCW Studio", description="Site name")
    SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS: list[str] = Field(
        default_factory=list
    )  # DERIVED: rebuilt in a model_validator from SITE_BASE_URL
    SOCIAL_AUTH_KEYCLOAK_EXTRA_DATA: list[Any] = Field(
        default_factory=lambda: [("id_token", "id_token")]
    )
    SOCIAL_AUTH_KEYCLOAK_SCOPE: list[str] = Field(
        default_factory=lambda: ["openid", "profile", "email"]
    )
    SOCIAL_AUTH_LOGIN_ERROR_URL: str = Field(default="main-index")
    SOCIAL_AUTH_LOGIN_REDIRECT_URL: str = Field(default="sites")
    SOCIAL_AUTH_PIPELINE: tuple[Any, ...] = Field(
        default=(
            "social_core.pipeline.social_auth.social_details",
            "social_core.pipeline.social_auth.social_uid",
            "social_core.pipeline.social_auth.auth_allowed",
            "social_core.pipeline.social_auth.social_user",
            "social_core.pipeline.user.get_username",
            "social_core.pipeline.social_auth.associate_by_email",
            "social_core.pipeline.user.create_user",
            "social_core.pipeline.social_auth.associate_user",
            "social_core.pipeline.social_auth.load_extra_data",
            "social_core.pipeline.user.user_details",
        )
    )  # TODO: refine type
    SOCIAL_AUTH_USER_FIELD_MAPPING: dict[str, Any] = Field(
        default_factory=lambda: {"fullname": "name"}
    )
    STATICFILES_DIRS: tuple[Any, ...] = Field(
        default=()
    )  # DERIVED: rebuilt in a model_validator from BASE_DIR
    STATIC_API_BASE_URL_DRAFT: str = Field(
        default="",
        description="The static api base url to use when building and deploying draft sites locally to minio",  # noqa: E501
    )  # dev-only
    STATIC_API_BASE_URL_LIVE: str = Field(
        default="",
        description="The static api base url to use when building and deploying live sites locally to minio",  # noqa: E501
    )  # dev-only
    STATIC_API_BASE_URL_TEST: str = Field(
        default="",
        description="The static api base url to use when building and deploying live sites locally to minio",  # noqa: E501
    )
    STATIC_ROOT: str = Field(default="staticfiles")
    STATIC_URL: str = Field(default="/static/")
    STATUS_TOKEN: str = Field(default="", description="Token to access the status API.")
    TEMPLATES: list[Any] = Field(
        default_factory=list
    )  # DERIVED: rebuilt in a model_validator from BASE_DIR
    TEST_ROOT_WEBSITE_NAME: str = Field(
        default="ocw-ci-test-www",
        description="The Website name for the site at the root of the test domain",
    )
    THREEPLAY_API_KEY: Any = Field(
        default=None, description="3play api key"
    )  # TODO: refine type
    THREEPLAY_BASE_TIMEOUT: int = Field(
        default=15,
        description="Base timeout in seconds for 3Play API requests, incremented on timeout retries",  # noqa: E501
    )
    THREEPLAY_CALLBACK_KEY: Any = Field(
        default=None, description="3play callback key"
    )  # TODO: refine type
    THREEPLAY_PROJECT_ID: int = Field(default=2, description="3play project id")
    TIME_ZONE: str = Field(default="UTC")
    TRANSCODE_JOB_TEMPLATE: str = Field(
        default="", description="Path to the transcoding job template"
    )
    UPDATE_MISSING_TRANSCRIPT_FREQUENCY: int = Field(
        default=43200,
        description="The frequency to check for transcripts for published videos with blank transcripts",  # noqa: E501
    )
    UPDATE_TAGGED_3PLAY_TRANSCRIPT_FREQUENCY: int = Field(
        default=3600,
        description="The frequency to check for videos tagged as updated in 3play",
    )
    UPDATE_WAYBACK_JOBS_STATUS_FREQUENCY: int = Field(
        default=21600,
        description="Frequency (in seconds) to check the status of Wayback Machine jobs",  # noqa: E501
    )
    USE_I18N: bool = Field(default=True)
    USE_TZ: bool = Field(default=True)
    USE_X_FORWARDED_HOST: bool = Field(
        default=False, description="Set HOST header to original domain accessed by user"
    )
    USE_X_FORWARDED_PORT: bool = Field(
        default=False, description="Use the PORT from original url accessed by user"
    )
    VERSION: str = Field(default="0.192.0")
    VIDEO_S3_THUMBNAIL_BUCKET: str = Field(
        default="", description="Bucket to be used for thumbnail generation"
    )
    VIDEO_S3_THUMBNAIL_PREFIX: str = Field(
        default="", description="Prefix for the thumbnail video"
    )
    VIDEO_S3_TRANSCODE_BUCKET: str = Field(
        default="", description="Bucket to be used for transcoding"
    )
    VIDEO_S3_TRANSCODE_ENDPOINT: str = Field(
        default="aws_mediaconvert_transcodes",
        description="Endpoint to be used for AWS MediaConvert",
    )
    VIDEO_S3_TRANSCODE_PREFIX: str = Field(
        default="", description="Prefix for the transcoded video"
    )
    VIDEO_S3_UPLOAD_PREFIX: str = Field(
        default="", description="Prefix for the source video"
    )
    VIDEO_TRANSCODE_QUEUE: str = Field(
        default="Default",
        description="Name of MediaConvert queue to use for transcoding",
    )
    WAYBACK_MACHINE_ACCESS_KEY: Any = Field(
        default=None, description="Access key for the Wayback Machine API"
    )  # TODO: refine type
    WAYBACK_MACHINE_SECRET_KEY: Any = Field(
        default=None, description="Secret key for the Wayback Machine API"
    )  # TODO: refine type
    WAYBACK_SUBMISSION_INTERVAL_DAYS: int = Field(
        default=30, description="Number of days between Wayback submissions"
    )
    WEBPACK_DEV_SERVER_HOST: str = Field(
        default="", description="The webpack dev server hostname, development only"
    )  # dev-only
    WEBPACK_DEV_SERVER_PORT: Any = Field(
        default=None, description="The webpack dev server port, development only"
    )  # TODO: refine type  # dev-only
    WEBPACK_DISABLE_LOADER_STATS: bool = Field(
        default=False,
        description="Disables the webpack loader, development environment only.",
    )  # dev-only
    WEBPACK_LOADER: dict[str, Any] = Field(
        default_factory=lambda: {
            "DEFAULT": {
                "CACHE": True,
                "BUNDLE_DIR_NAME": "bundles/",
                "STATS_FILE": None,
                "POLL_INTERVAL": 0.1,
                "TIMEOUT": None,
                "IGNORE": [".+\\.hot-update\\.+", ".+\\.js\\.map"],
            }
        }
    )  # DERIVED: CACHE/STATS_FILE rebuilt in a model_validator
    WEBPACK_USE_DEV_SERVER: bool = Field(
        default=False, description="Enables the webpack devserver, development only"
    )  # dev-only
    WSGI_APPLICATION: str = Field(default="main.wsgi.application")
    YT_ACCESS_TOKEN: str = Field(default="", description="Youtube access token")
    YT_CATEGORY_ID: int = Field(
        default=27, description="Default video category ID for youtube"
    )
    YT_CLIENT_ID: str = Field(default="", description="Youtube Client ID")
    YT_CLIENT_SECRET: str = Field(default="", description="Youtube client secret key")
    YT_FIELD_CAPTIONS: str = Field(
        default="video_files.video_captions_file",
        description="The site config metadata field for the captions URL",
    )
    YT_FIELD_CAPTIONS_RESOURCE: str = Field(
        default="video_files.video_captions_resource",
        description="The site config metadata field for the captions resource",
    )
    YT_FIELD_DESCRIPTION: str = Field(
        default="video_metadata.youtube_description",
        description="The site config metadata field for YouTube description",
    )
    YT_FIELD_ID: str = Field(
        default="video_metadata.youtube_id",
        description="The site config metadata field for YouTube ID",
    )
    YT_FIELD_SPEAKERS: str = Field(
        default="video_metadata.video_speakers",
        description="The site config metadata field for YouTube speakers",
    )
    YT_FIELD_TAGS: str = Field(
        default="video_metadata.video_tags",
        description="The site config metadata field for YouTube video tags",
    )
    YT_FIELD_THUMBNAIL: str = Field(
        default="video_files.video_thumbnail_file",
        description="The site config metadata field for YouTube thumbnail URL",
    )
    YT_FIELD_TRANSCRIPT: str = Field(
        default="video_files.video_transcript_file",
        description="The site config metadata field for the transcript URL",
    )
    YT_FIELD_TRANSCRIPT_RESOURCE: str = Field(
        default="video_files.video_transcript_resource",
        description="The site config metadata field for the transcript resource",
    )
    YT_PROJECT_ID: str = Field(default="", description="Youtube project ID")
    YT_REFRESH_TOKEN: str = Field(default="", description="YT_REFRESH_TOKEN")
    YT_STATUS_UPDATE_FREQUENCY: int = Field(
        default=60,
        description="The frequency to check for status updates on uploaded youtube videos",  # noqa: E501
    )
    YT_UPLOAD_FREQUENCY: int = Field(
        default=60, description="The frequency to check for videos to upload to Youtube"
    )
    YT_UPLOAD_LIMIT: int = Field(
        default=50, description="Max Youtube uploads allowed per day"
    )

    # ===== required fields (no default; must be supplied at runtime) =====
    SECRET_KEY: str = Field(description="Django secret key.")
    ENVIRONMENT: str = Field(
        validation_alias="OCW_STUDIO_ENVIRONMENT",
        description=(
            "The execution environment that the app is in (e.g. dev, staging, prod)"
        ),
    )
    SITE_BASE_URL: str = Field(
        validation_alias="OCW_STUDIO_BASE_URL",
        description=(
            "Base url for the application in the format PROTOCOL://HOSTNAME[:PORT]"
        ),
    )
    MAILGUN_SENDER_DOMAIN: str = Field(
        description="The domain to send mailgun email through"
    )
    MAILGUN_KEY: str = Field(
        description="The token for authenticating against the Mailgun API"
    )
    SOCIAL_AUTH_KEYCLOAK_KEY: str = Field(
        description="Keycloak client ID for social auth"
    )
    SOCIAL_AUTH_KEYCLOAK_SECRET: str = Field(
        description="Keycloak client secret for social auth"
    )
    SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY: str = Field(
        description="Keycloak realm public key for social auth"
    )
    SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: str = Field(
        description="Keycloak authorization URL for social auth"
    )
    SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: str = Field(
        description="Keycloak access token URL for social auth"
    )

    # ===== main/envs.py (bypasses the mitol EnvParser registry) =====
    OCW_TEST_SITE_SLUGS: list[str] = Field(
        default_factory=list,
        description="Website slugs used for the test/staging root site",
    )
    OCW_EXTRA_THEMES_BASE_URLS: dict[str, str] = Field(
        default_factory=dict,
        description="Extra Hugo theme slug -> base URL mapping",
    )
    OCW_EXTRA_THEMES_GTM_IDS: dict[str, str] = Field(
        default_factory=dict,
        description="Extra Hugo theme slug -> Google Tag Manager ID mapping",
    )

    # ===== dynamic / derived-source special cases =====
    FEATURES: dict[str, bool] = Field(
        default_factory=_scan_feature_flags,
        description=(
            "Feature flags scanned from FEATURE_* environment variables at load "
            "time (re-scanned on every instantiation, matching get_features())"
        ),
    )
    GITHUB_APP_PRIVATE_KEY: str | bytes = Field(
        default="",
        description="A github app private key for authentication",
    )  # DERIVED: unicode-escape decode/encode roundtrip applied in a model_validator;
    # the field holds a `str` as configured but a `bytes` value once validated,
    # matching main/settings.py's runtime behavior.
    OPEN_CATALOG_URLS: list[str] = Field(
        default_factory=lambda: [""],
        description="Open catalog urls",
    )

    # ===== model_validators reproducing main/settings.py derivations =====

    @model_validator(mode="after")
    def _validate_playwright_image_arch(self) -> AqueductSettings:
        """Reject any PLAYWRIGHT_IMAGE_ARCH other than "" or "amd64"."""
        if self.PLAYWRIGHT_IMAGE_ARCH not in {"", "amd64"}:
            msg = (
                "PLAYWRIGHT_IMAGE_ARCH must be 'amd64' or unset, "
                f"got {self.PLAYWRIGHT_IMAGE_ARCH!r}"
            )
            raise ImproperlyConfigured(msg)
        return self

    @model_validator(mode="after")
    def _transform_github_app_private_key(self) -> AqueductSettings:
        """Apply the same unicode-escape decode/encode roundtrip as main/settings.py."""
        self.GITHUB_APP_PRIVATE_KEY = (
            self.GITHUB_APP_PRIVATE_KEY.encode().decode("unicode_escape").encode()
        )
        return self

    @model_validator(mode="after")
    def _build_databases(self) -> AqueductSettings:
        """Derive DATABASES/DEFAULT_DATABASE_CONFIG from DATABASE_URL."""
        config = dj_database_url.parse(self.DATABASE_URL)
        config["CONN_MAX_AGE"] = self.OCW_STUDIO_DB_CONN_MAX_AGE
        config["DISABLE_SERVER_SIDE_CURSORS"] = self.OCW_STUDIO_DB_DISABLE_SS_CURSORS
        config["OPTIONS"] = (
            {} if self.OCW_STUDIO_DB_DISABLE_SSL else {"sslmode": "require"}
        )
        self.DEFAULT_DATABASE_CONFIG = config
        self.DATABASES = {"default": config}
        return self

    @model_validator(mode="after")
    def _build_celery_broker_urls(self) -> AqueductSettings:
        """Fall back broker/result URLs to REDISCLOUD_URL or REDIS_URL."""
        redis_url = self.REDISCLOUD_URL or self.REDIS_URL
        if self.CELERY_BROKER_URL is None:
            self.CELERY_BROKER_URL = redis_url
        if self.CELERY_RESULT_BACKEND is None:
            self.CELERY_RESULT_BACKEND = redis_url
        return self

    @model_validator(mode="after")
    def _build_caches(self) -> AqueductSettings:
        """Rebuild CACHES so the redis backend reflects CELERY_BROKER_URL."""
        self.CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            "redis": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": self.CELERY_BROKER_URL,
                "OPTIONS": {
                    "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    "CONNECTION_POOL_KWARGS": {
                        "max_connections": self.REDIS_MAX_CONNECTIONS
                    },
                },
            },
        }
        return self

    @model_validator(mode="after")
    def _build_installed_apps_and_middleware(self) -> AqueductSettings:
        """Reproduce the conditional INSTALLED_APPS/MIDDLEWARE composition."""
        installed_apps = [
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            "django.contrib.sites",
            "guardian",
            "hijack",
            "hijack.contrib.admin",
            "safedelete",
            "rest_framework",
            "social_django",
            "robots",
            "anymail",
            "bulk_update_or_create",
            "main",
            "users",
            "websites",
            "news",
            "content_sync",
            "gdrive_sync",
            "videos",
            "external_resources",
            "django_removals",
            "mitol.common.apps.CommonApp",
            "mitol.authentication.apps.AuthenticationApp",
            "mitol.mail.apps.MailApp",
        ]
        if self.ENVIRONMENT not in PRODUCTION_NAMES:
            installed_apps.append("localdev")
        if not self.DISABLE_WEBPACK_LOADER_STATS:
            installed_apps.append("webpack_loader")

        middleware: list[Any] = [
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "django.contrib.sites.middleware.CurrentSiteMiddleware",
            "main.middleware.CachelessAPIMiddleware",
            "hijack.middleware.HijackUserMiddleware",
        ]

        if self.DEBUG:
            installed_apps.append("nplusone.ext.django")
            middleware.append("nplusone.ext.django.NPlusOneMiddleware")

        if self.MIDDLEWARE_FEATURE_FLAG_QS_PREFIX:
            # NOTE: main/settings.py appends a *list* here rather than extending
            # (pre-existing behavior in the original module); preserved as-is.
            middleware.append(
                [
                    "main.middleware.QueryStringFeatureFlagMiddleware",
                    "main.middleware.CookieFeatureFlagMiddleware",
                ]
            )

        if self.DEBUG:
            installed_apps.append("debug_toolbar")
            middleware.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

        self.INSTALLED_APPS = installed_apps
        self.MIDDLEWARE = middleware
        return self

    @model_validator(mode="after")
    def _build_celery_beat_schedule(self) -> AqueductSettings:
        """Rebuild CELERY_BEAT_SCHEDULE from the *_FREQUENCY fields."""
        schedule: dict[str, Any] = {
            "update-youtube-statuses": {
                "task": "videos.tasks.update_youtube_statuses",
                "schedule": self.YT_STATUS_UPDATE_FREQUENCY,
            },
            "upload-youtube-videos": {
                "task": "videos.tasks.upload_youtube_videos",
                "schedule": self.YT_UPLOAD_FREQUENCY,
            },
            "update-transcripts-for-updated-videos": {
                "task": "videos.tasks.update_transcripts_for_updated_videos",
                "schedule": self.UPDATE_TAGGED_3PLAY_TRANSCRIPT_FREQUENCY,
            },
            "attempt-to-update-missing-transcripts": {
                "task": "videos.tasks.attempt_to_update_missing_transcripts",
                "schedule": self.UPDATE_MISSING_TRANSCRIPT_FREQUENCY,
            },
            "check_incomplete_publish_build_statuses": {
                "task": "content_sync.tasks.check_incomplete_publish_build_statuses",
                "schedule": self.PUBLISH_INCOMPLETE_BUILD_STATUS_FREQUENCY,
            },
        }
        if self.ENABLE_WAYBACK_TASKS:
            schedule["update-wayback-jobs-status"] = {
                "task": "external_resources.tasks.update_wayback_jobs_status_batch",
                "schedule": self.UPDATE_WAYBACK_JOBS_STATUS_FREQUENCY,
            }
        if self.ENABLE_CHECK_EXTERNAL_RESOURCE_TASK:
            schedule["check-broken-external-urls"] = {
                "task": "external_resources.tasks.check_external_resources_for_breakages",  # noqa: E501
                "schedule": self.CHECK_EXTERNAL_RESOURCE_STATUS_FREQUENCY,
            }
        self.CELERY_BEAT_SCHEDULE = schedule
        return self

    @model_validator(mode="after")
    def _validate_s3_credentials(self) -> AqueductSettings:
        """Require S3 credentials to be complete whenever OCW_STUDIO_USE_S3 is set."""
        if self.OCW_STUDIO_USE_S3 and (
            not self.AWS_ACCESS_KEY_ID
            or not self.AWS_SECRET_ACCESS_KEY
            or not self.AWS_STORAGE_BUCKET_NAME
        ):
            msg = (
                "You have enabled S3 support, but are missing one of "
                "AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, or AWS_STORAGE_BUCKET_NAME"
            )
            raise ImproperlyConfigured(msg)
        return self

    @model_validator(mode="after")
    def _validate_extra_theme_gtm_ids(self) -> AqueductSettings:
        """Reject GTM ids for themes not in OCW_EXTRA_COURSE_THEMES."""
        unknown = set(self.OCW_EXTRA_THEMES_GTM_IDS) - set(self.OCW_EXTRA_COURSE_THEMES)
        if unknown:
            msg = (
                "OCW_EXTRA_THEMES_GTM_IDS contains theme slugs that are not "
                f"configured in OCW_EXTRA_COURSE_THEMES: {', '.join(sorted(unknown))}"
            )
            raise ImproperlyConfigured(msg)
        return self

    @model_validator(mode="after")
    def _build_misc_derived(self) -> AqueductSettings:
        """Rebuild the remaining settings derived from other fields."""
        self.ADMINS = (("Admins", self.ADMIN_EMAIL),) if self.ADMIN_EMAIL else ()
        self.INTERNAL_IPS = (self.HOST_IP,)
        self.SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS = [urlparse(self.SITE_BASE_URL).netloc]
        self.ANYMAIL = {
            "MAILGUN_API_KEY": self.MAILGUN_KEY,
            "MAILGUN_SENDER_DOMAIN": self.MAILGUN_SENDER_DOMAIN,
        }
        self.STATICFILES_DIRS = (os.path.join(self.BASE_DIR, "static"),)  # noqa: PTH118
        self.TEMPLATES = [
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "DIRS": [f"{self.BASE_DIR}/templates"],
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.debug",
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                    ],
                },
            },
        ]
        webpack_loader = dict(self.WEBPACK_LOADER)
        webpack_loader["DEFAULT"] = {
            **webpack_loader["DEFAULT"],
            "CACHE": not self.DEBUG,
            "STATS_FILE": os.path.join(self.BASE_DIR, "webpack-stats.json"),  # noqa: PTH118
        }
        self.WEBPACK_LOADER = webpack_loader
        if self.OCW_STUDIO_USE_S3:
            self.STORAGES = {
                "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
                "staticfiles": {
                    "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
                },
            }
        return self


class DevAqueductSettings(AqueductSettings):
    """Local-dev variant: fills missing values from Vault via OIDC."""

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,  # noqa: ARG003
        file_secret_settings,  # noqa: ARG003
    ):
        """Layer a Vault OIDC source under env vars so devs skip a .env file."""
        from django_aqueduct.sources.vault import VaultSettingsSource  # noqa: PLC0415

        # NOTE: VAULT_AQUEDUCT_PATH and the default OIDC role ("ocw-studio") are
        # placeholders. They need to be confirmed against the live Vault server
        # (e.g. `vault kv list secret-ocw-studio/`) before this is used for real;
        # nothing in this repo tells us the exact secret path or role name.
        return (
            init_settings,
            env_settings,
            VaultSettingsSource(
                settings_cls,
                vault_url=os.environ["VAULT_ADDR"],
                vault_path=os.environ.get("VAULT_AQUEDUCT_PATH", ""),
                mount_point="secret-ocw-studio",
                kv_version="2",
                auth_method="oidc",
                role=os.environ.get("VAULT_AQUEDUCT_ROLE", "ocw-studio"),
            ),
        )
