# Generated by Django 4.2.15 on 2024-10-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0057_website_draft_build_date_website_live_build_date"),
        ("external_resources", "0002_alter_externalresourcestate_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalresourcestate",
            name="referencing_pages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Pages that reference this external resource",
                related_name="referenced_external_resources",
                to="websites.websitecontent",
            ),
        ),
        migrations.AlterField(
            model_name="externalresourcestate",
            name="last_checked",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Last time when this resource was checked for breakages",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="externalresourcestate",
            name="status",
            field=models.CharField(
                choices=[
                    ("unchecked", "Unchecked or pending check"),
                    ("valid", "Either URL or backup URL is valid"),
                    ("broken", "Both URL and backup URL are broken"),
                    (
                        "check_failed",
                        "Last attempt to check the resource failed unexpectedly",
                    ),
                ],
                default="unchecked",
                help_text="The status of this external resource",
                max_length=16,
            ),
        ),
    ]
