""" Constants for websites """

CONTENT_TYPE_PAGE = "page"
CONTENT_TYPE_FILE = "file"

COURSE_HOME = "course-home"

WEBSITE_SOURCE_STUDIO = "studio"
WEBSITE_SOURCE_OCW_IMPORT = "ocw-import"
WEBSITE_SOURCES = [WEBSITE_SOURCE_STUDIO, WEBSITE_SOURCE_OCW_IMPORT]

STARTER_SOURCE_GITHUB = "github"
STARTER_SOURCE_LOCAL = "local"
STARTER_SOURCES = [STARTER_SOURCE_GITHUB, STARTER_SOURCE_LOCAL]

COURSE_STARTER_SLUG = "course"

WEBSITE_CONFIG_FILENAME = "ocw-studio.yml"
