# Generated by Django 3.1.6 on 2021-04-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("websites", "0017_rename_filepath"),
        ("content_sync", "0002_backpopulate_content_sync_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentsyncstate",
            name="content",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_sync_state",
                to="websites.websitecontent",
            ),
        ),
    ]
