# Generated by Django 3.1.14 on 2023-03-15 20:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('content_sync', '0004_content_not_nullable'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contentsyncstate',
            managers=[
                ('bulk_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
