# Generated by Django 3.1.14 on 2023-03-15 20:08

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_sync", "0004_content_not_nullable"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contentsyncstate",
            managers=[
                ("bulk_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
