course:
  collections:
    - name: page
      label: Page
      category: Content
      folder: content
      fields:
        - {"label": "Title", "name": "title", "widget": "string", "required": true}
        - {"label": "Content", "name": "content", "widget": "markdown", "required": true}

    - name: resource
      label: Resource
      category: Content
      folder: content
      fields:
        - {"label": "Title", "name": "title", "widget": "string", "required": true}
        - {"label": "Description", "name": "description", "widget": "text", "required": true}
        - {"label": "File", "name": "file", "widget": "file", "required": true}

    - name: metadata
      label: Site Metadata
      category: Settings
      file: data/metadata.json
      fields:
        - { "label": "Course Title", "name": "title", "widget": "text", "required": true }
        - {
          "label": "Course Description",
          "name": "description",
          "widget": "markdown",
          "minimal": true,
          "help": "A description of the course that will be shown on the course site home page."
        }
        - { "label": "Tags", "default": ["Design"], "max": 3, "min": 1, "multiple": true, "name": "tags", "options": ["Design", "UX", "Dev"], "widget": "select" }
        - { label: "Align Content", name: "align", widget: "select", options: ["left", "center", "right"]}
