# Generated by Django 3.1.12 on 2021-08-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
        ("gdrive_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivefile",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="videos.video",
            ),
        ),
    ]
