# Generated by Django 3.1.12 on 2021-09-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdrive_sync", "0003_drivefile_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="driveapiquerytracker",
            name="for_video",
            field=models.BooleanField(default=True),
        ),
    ]
