# Generated by Django 3.1.12 on 2021-09-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gdrive_sync", "0003_drivefile_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="driveapiquerytracker",
            name="for_video",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="driveapiquerytracker",
            name="api_call",
            field=models.CharField(
                choices=[("files", "files"), ("changes", "changes")], max_length=128
            ),
        ),
        migrations.AlterUniqueTogether(
            name="driveapiquerytracker",
            unique_together={("api_call", "for_video")},
        ),
    ]
