# Generated by Django 3.1.12 on 2021-09-30 13:25

from django.db import migrations, models


def remove_video_tracker(apps, schema_editor):
    """Remove the video-specific tracker"""
    DriveApiQueryTracker = apps.get_model("gdrive_sync", "DriveApiQueryTracker")
    DriveApiQueryTracker.objects.filter(for_video=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("gdrive_sync", "0004_driveapiquerytracker_for_video"),
    ]

    operations = [
        migrations.RunPython(remove_video_tracker, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="driveapiquerytracker",
            name="api_call",
            field=models.CharField(
                choices=[("files", "files"), ("changes", "changes")],
                max_length=128,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="driveapiquerytracker",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="driveapiquerytracker",
            name="for_video",
        ),
    ]
