# Generated by Django 3.1.13 on 2021-10-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gdrive_sync", "0005_driveapiquerytracker_remove_for_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivefile",
            name="checksum",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
