# Generated by Django 3.1.13 on 2021-10-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdrive_sync", "0006_drivefile_null_checksum"),
    ]

    operations = [
        migrations.AddField(
            model_name="drivefile",
            name="sync_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drivefile",
            name="sync_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
