# Generated by Django 3.1.14 on 2023-06-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrive_sync', '0007_gdrive_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
