# Generated by Django 3.2.19 on 2023-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gdrive_sync", "0008_drivefile_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivefile",
            name="size",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
