---
resource_types:
  - name: http-resource
    type: docker-image
    source:
      repository: jgriff/http-resource
      tag: latest
resources:
  - name: ocw-hugo-themes
    type: s3
    source:
      bucket: ol-eng-artifacts
      regexp: ocw-hugo-themes\/release-candidate\/ocw-hugo-themes-(.*).tgz
  - name: ocw-static-version
    type: s3
    source:
      bucket: ((ocw-bucket))
      regexp: static\/version\.(.*)\.txt
      initial_path: static/version.0.txt
  - name: course-markdown
    type: git
    source:
      uri: ((markdown-uri))((git-private-key-var))
      branch: ((ocw-site-repo-branch))
  - name: ocw-hugo-projects
    type: git
    source:
      uri: ((ocw-hugo-projects-uri))
      branch: ((ocw-hugo-projects-branch))
  - name: ocw-studio-webhook
    type: http-resource
    source:
        url: ((ocw-studio-url))/api/websites/((site-name))/pipeline_status/
        method: POST
        headers:
            Content-Type: "application/json"
            Authorization: "Bearer ((api-token))"
        text: "{json}"
        out_only: true
jobs:
  - name: build-ocw-site
    serial: true
    plan:
      - try:
          put: ocw-studio-webhook
          timeout: 5m
          attempts: 3
          params:
            json: |
              {
                "version": "((version))",
                "status": "started"
              }
      - get: ocw-hugo-themes
        trigger: ((theme-created-trigger))
        timeout: 5m
        on_failure:
          try:
            put: ocw-studio-webhook
            params:
                json: |
                  {
                    "version": "((version))",
                    "status": "errored"
                  }
      - get: ocw-static-version
        trigger: ((theme-deployed-trigger))
        timeout: 5m
        attempts: 3
        on_failure:
          try:
            put: ocw-studio-webhook
            params:
                json: |
                  {
                    "version": "((version))",
                    "status": "errored"
                  }
      - get: ocw-hugo-projects
        trigger: true
        timeout: 5m
        attempts: 3
        on_failure:
          try:
            put: ocw-studio-webhook
            params:
                json: |
                  {
                    "version": "((version))",
                    "status": "errored"
                  }
      - get: course-markdown
        trigger: false
        timeout: 5m
        attempts: 3
        on_failure:
          try:
            put: ocw-studio-webhook
            params:
                json: |
                  {
                    "version": "((version))",
                    "status": "errored"
                  }
      - task: build-course-task
        timeout: 20m
        attempts: 3
        params:
          OCW_STUDIO_BASE_URL: ((ocw-studio-url))
          STATIC_API_BASE_URL: ((static-api-base-url))
          OCW_IMPORT_STARTER_SLUG: ((ocw-import-starter-slug))
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: mitodl/ocw-course-publisher, tag: latest}
          inputs:
            - name: ocw-hugo-themes
            - name: course-markdown
            - name: ocw-hugo-projects
          outputs:
            - name: course-markdown
            - name: ocw-hugo-themes
          run:
            dir: course-markdown
            path: sh
            args:
            - -exc
            - |
              mkdir -p ../ocw-hugo-themes/theme
              tar -xvzf ../ocw-hugo-themes/ocw-hugo-themes-*.tgz -C ../ocw-hugo-themes/theme
              hugo --config ../ocw-hugo-projects/((config-slug))/config.yaml --baseUrl /((base-url)) --themesDir ../ocw-hugo-themes/theme
        on_failure:
          try:
            put: ocw-studio-webhook
            attempts: 3
            params:
                json: |
                  {
                    "version": "((version))",
                    "status": "errored"
                  }
      - task: copy-s3-buckets
        timeout: 20m
        attempts: 3
        config:
          inputs:
            - name: ocw-hugo-themes
            - name: course-markdown
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: amazon/aws-cli, tag: latest}
          run:
            path: sh
            args:
            - -exc
            - |
              aws s3 sync course-markdown/public s3://((ocw-bucket))/((base-url)) --metadata site-id=((site-name))
              aws s3 sync s3://((ocw-studio-bucket))/((site-url)) s3://((ocw-bucket))/((site-url)) --metadata site-id=((site-name))
              if [[ "((base-url))" == "" ]]; then aws s3 sync ocw-hugo-themes/theme/base-theme/dist s3://((ocw-bucket)) --metadata site-id=((site-name)); fi
        on_failure:
          try:
            put: ocw-studio-webhook
            attempts: 3
            params:
                json: |
                  {
                    "version": "((version))",
                    "status": "errored"
                  }
      - task: clear-cdn-cache
        timeout: 5m
        attempts: 3
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: curlimages/curl}
          run:
            path: curl
            args:
              - -f
              - -X
              - POST
              - -H
              - 'Fastly-Key: ((fastly.api_token))'((purge_header))
              - https://api.fastly.com/service/((fastly.service_id))/((purge-url))
        on_success:
          try:
            put: ocw-studio-webhook
            attempts: 3
            params:
                json: |
                  {
                    "version": "((version))",
                    "status": "succeeded"
                  }
        on_failure:
          try:
            put: ocw-studio-webhook
            attempts: 3
            params:
                json: |
                  {
                    "version": "((version))",
                    "status": "errored"
                  }
