---
resource_types:
  - name: http-resource
    type: docker-image
    source:
      repository: jgriff/http-resource
      tag: latest
  - name: s3-resource-iam
    type: docker-image
    source:
      repository: governmentpaas/s3-resource
      tag: latest
resources:
  - name: webpack-json
    type: s3-resource-iam
    check_every: never
    source:
      endpoint: http://10.1.0.100:9000
      access_key_id: ((minio-root-user))
      secret_access_Key: ((minio-root-password))
      bucket: ((artifacts-bucket))
      versioned_file: ocw-hugo-themes/((ocw-hugo-themes-branch))/webpack.json
  - name: course-markdown
    type: git
    check_every: never
    source:
      uri: ((markdown-uri))((git-private-key-var))
      branch: ((ocw-site-repo-branch))
  - name: ocw-hugo-themes
    type: git
    check_every: never
    source:
      uri: ((ocw-hugo-themes-uri))
      branch: ((ocw-hugo-themes-branch))
  - name: ocw-hugo-projects
    type: git
    check_every: never
    source:
      uri: ((ocw-hugo-projects-uri))
      branch: ((ocw-hugo-projects-branch))
  - name: ocw-studio-webhook
    type: http-resource
    check_every: never
    source:
        url: ((ocw-studio-url))/api/websites/((site-name))/pipeline_status/
        method: POST
        headers:
            Content-Type: "application/json"
            Authorization: "Bearer ((api-token))"
        out_only: true
jobs:
  - name: build-ocw-site
    serial: true
    plan:
      - try:
          put: ocw-studio-webhook
          timeout: 1m
          attempts: 3
          params:
            text: |
              {
                "version": "((pipeline_name))",
                "status": "started"
              }
      - get: webpack-json
        trigger: false
        on_failure:
          try:
            do:
            - put: ocw-studio-webhook
              timeout: 1m
              params:
                  text: |
                    {
                      "version": "((pipeline_name))",
                      "status": "errored"
                    }
      - get: ocw-hugo-themes
        trigger: false
        timeout: 5m
        on_failure:
          try:
            do:
            - put: ocw-studio-webhook
              timeout: 1m
              params:
                  text: |
                    {
                      "version": "((pipeline_name))",
                      "status": "errored"
                    }
      - get: ocw-hugo-projects
        trigger: false
        timeout: 5m
        attempts: 3
        on_failure:
          try:
            do:
            - put: ocw-studio-webhook
              timeout: 1m
              params:
                  text: |
                    {
                      "version": "((pipeline_name))",
                      "status": "errored"
                    }
      - get: course-markdown
        trigger: false
        timeout: 5m
        attempts: 3
        on_failure:
          try:
            do:
            - put: ocw-studio-webhook
              timeout: 1m
              params:
                  text: |
                    {
                      "version": "((pipeline_name))",
                      "status": "errored"
                    }
      - task: build-course-task
        timeout: 20m
        attempts: 3
        params:
          API_BEARER_TOKEN: ((api-token))
          GTM_ACCOUNT_ID: ((gtm-account-id))
          OCW_STUDIO_BASE_URL: ((ocw-studio-url))
          STATIC_API_BASE_URL: ((static-api-base-url))
          OCW_IMPORT_STARTER_SLUG: ((ocw-import-starter-slug))
          SITEMAP_DOMAIN: ((sitemap-domain))
          RESOURCE_BASE_URL: ((resource-base-url))
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: mitodl/ocw-course-publisher, tag: 0.2}
          inputs:
            - name: ocw-hugo-themes
            - name: course-markdown
            - name: ocw-hugo-projects
            - name: webpack-json
          outputs:
            - name: course-markdown
            - name: ocw-hugo-themes
          run:
            dir: course-markdown
            path: sh
            args:
            - -exc
            - |
              cp ../webpack-json/webpack.json ../ocw-hugo-themes/base-theme/data
              hugo --config ../ocw-hugo-projects/((config-slug))/config.yaml --baseUrl /((base-url)) --themesDir ../ocw-hugo-themes/ ((build-drafts))
        on_failure:
          try:
            do:
            - put: ocw-studio-webhook
              timeout: 1m
              attempts: 3
              params:
                  text: |
                    {
                      "version": "((pipeline_name))",
                      "status": "errored"
                    }
      - task: copy-s3-buckets
        timeout: 20m
        attempts: 3
        config:
          inputs:
            - name: course-markdown
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: amazon/aws-cli, tag: latest}
          params:
            AWS_ACCESS_KEY_ID: ((minio-root-user))
            AWS_SECRET_ACCESS_KEY: ((minio-root-password))
          run:
            path: sh
            args:
            - -exc
            - |
              aws s3 --endpoint-url http://10.1.0.100:9000 sync s3://((ocw-studio-bucket))/((s3-path)) s3://((ocw-bucket))/((site-url)) --metadata site-id=((site-name))              
              aws s3 --endpoint-url http://10.1.0.100:9000 sync course-markdown/public s3://((ocw-bucket))/((base-url)) --metadata site-id=((site-name))
        on_success:
          try:
            do:
            - put: ocw-studio-webhook
              timeout: 1m
              attempts: 3
              params:
                text: |
                  {
                    "version": "((pipeline_name))",
                    "status": "succeeded"
                  }
        on_failure:
          try:
            do:
            - put: ocw-studio-webhook
              timeout: 1m
              attempts: 3
              params:
                  text: |
                    {
                      "version": "((pipeline_name))",
                      "status": "errored"
                    }
