---
resource_types:
 # START NON-DEV
  - name: slack-alert
    type: registry-image
    source:
      repository: arbourd/concourse-slack-alert-resource
      tag: v0.15.0
  # END NON-DEV
resources:
  # START NON-DEV
- name: slack-webhook
  type: slack-alert
  check_every: never
  source:
    url: ((slack-url))
    disabled: false
  # END NON-DEV
- name: ocw-hugo-themes
  type: git
  source:
    uri: ((ocw-hugo-themes-uri))
    branch: ((ocw-hugo-themes-branch))
jobs:
- name: build-theme-assets
  serial: true
  plan:
  - get: ocw-hugo-themes
    # START NON-DEV
    trigger: true
    # END NON-DEV
  - task: build-ocw-hugo-themes
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: mitodl/ocw-course-publisher, tag: 0.4}
      inputs:
      - name: ocw-hugo-themes
      outputs:
      - name: ocw-hugo-themes
      params:
        SEARCH_API_URL: ((search-api-url))
        SENTRY_DSN: ((ocw-hugo-themes-sentry-dsn))
      run:
        path: sh
        args:
        - -exc
        - |
          cd ocw-hugo-themes
          yarn install --immutable
          npm run build:webpack
          npm run build:githash
  - task: copy-s3-buckets
    timeout: 20m
    attempts: 3
    config:
      inputs:
        - name: ocw-hugo-themes
      platform: linux
      # START DEV-ONLY
      params:
        AWS_ACCESS_KEY_ID: ((minio-root-user))
        AWS_SECRET_ACCESS_KEY: ((minio-root-password))
      # END DEV-ONLY
      image_resource:
        type: registry-image
        source: {repository: amazon/aws-cli, tag: latest}
      run:
        path: sh
        args:
          - -exc
          - |
            aws s3((cli-endpoint-url)) cp ocw-hugo-themes/base-theme/dist s3://((ocw-bucket-draft)) --recursive --metadata site-id=ocw-hugo-themes
            aws s3((cli-endpoint-url)) cp ocw-hugo-themes/base-theme/dist s3://((ocw-bucket-live)) --recursive --metadata site-id=ocw-hugo-themes
            aws s3((cli-endpoint-url)) cp ocw-hugo-themes/base-theme/data/webpack.json s3://((artifacts-bucket))/ocw-hugo-themes/((ocw-hugo-themes-branch))/webpack.json --metadata site-id=ocw-hugo-themes
  # START NON-DEV
  - task: clear-cdn-cache-draft
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: curlimages/curl}
      run:
        path: curl
        args:
          - -f
          - -X
          - POST
          - -H
          - 'Fastly-Key: ((fastly_draft.api_token))'((purge_header))
          - https://api.fastly.com/service/((fastly_draft.service_id))/purge/ocw-hugo-themes
  - task: clear-cdn-cache-live
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: curlimages/curl}
      run:
        path: curl
        args:
          - -f
          - -X
          - POST
          - -H
          - 'Fastly-Key: ((fastly_live.api_token))'((purge_header))
          - https://api.fastly.com/service/((fastly_live.service_id))/purge/ocw-hugo-themes
  # END NON-DEV
  # START NON-DEV
  on_failure:
    try:
      do:
      - put: slack-webhook
        timeout: 1m
        params:
          alert_type: failed
          text: |
            Failed to build theme assets.

            Append `((atc-search-params))` to the url below for more details.
  on_abort:
    try:
      do:
      - put: slack-webhook
        timeout: 1m
        params:
          alert_type: aborted
          text: |
            User aborted while building theme assets.

            Append `((atc-search-params))` to the url below for more details.
   # END NON-DEV
