---
resources:
- name: ocw-hugo-themes
  type: git
  source:
    uri: ((ocw-hugo-themes-uri))
    branch: ((ocw-hugo-themes-branch))
jobs:
- name: build-theme-assets
  serial: true
  plan:
  - get: ocw-hugo-themes
    # START NON-DEV
    trigger: true
    # END NON-DEV
  - task: build-ocw-hugo-themes
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: mitodl/ocw-course-publisher, tag: 0.3}
      inputs:
      - name: ocw-hugo-themes
      outputs:
      - name: ocw-hugo-themes
      params:
        SEARCH_API_URL: ((search-api-url))
      run:
        path: sh
        args:
        - -exc
        - |
          cd ocw-hugo-themes
          yarn install --immutable
          npm run build:webpack
          npm run build:githash
  - task: copy-s3-buckets
    timeout: 20m
    attempts: 3
    config:
      inputs:
        - name: ocw-hugo-themes
      platform: linux
      # START DEV-ONLY
      params:
        AWS_ACCESS_KEY_ID: ((minio-root-user))
        AWS_SECRET_ACCESS_KEY: ((minio-root-password))
      # END DEV-ONLY
      image_resource:
        type: docker-image
        source: {repository: amazon/aws-cli, tag: latest}
      run:
        path: sh
        args:
          - -exc
          - |
            aws s3((cli-endpoint-url)) cp ocw-hugo-themes/base-theme/dist s3://((ocw-bucket-draft)) --recursive --metadata site-id=ocw-hugo-themes
            aws s3((cli-endpoint-url)) cp ocw-hugo-themes/base-theme/dist s3://((ocw-bucket-live)) --recursive --metadata site-id=ocw-hugo-themes
            aws s3((cli-endpoint-url)) cp ocw-hugo-themes/base-theme/data/webpack.json s3://((artifacts-bucket))/ocw-hugo-themes/((ocw-hugo-themes-branch))/webpack.json --metadata site-id=ocw-hugo-themes
  # START NON-DEV
  - task: clear-cdn-cache-draft
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: curlimages/curl}
      run:
        path: curl
        args:
          - -f
          - -X
          - POST
          - -H
          - 'Fastly-Key: ((fastly_draft.api_token))'((purge_header))
          - https://api.fastly.com/service/((fastly_draft.service_id))/purge/ocw-hugo-themes
  - task: clear-cdn-cache-live
    timeout: 5m
    attempts: 3
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: curlimages/curl}
      run:
        path: curl
        args:
          - -f
          - -X
          - POST
          - -H
          - 'Fastly-Key: ((fastly_live.api_token))'((purge_header))
          - https://api.fastly.com/service/((fastly_live.service_id))/purge/ocw-hugo-themes
  # END NON-DEV