---
resource_types:
- name: rclone
  type: docker-image
  source:
    repository: mitodl/concourse-rclone-resource
    tag: latest
resources:
- name: ocw-hugo-themes
  type: git
  source:
    uri: https://github.com/mitodl/ocw-hugo-themes.git
    branch: ((hugo-theme-branch))
- name: ocw-artifacts
  type: rclone
  source:
    config: |
      [s3-remote]
      type = s3
      provider = AWS
      env_auth = true
      region = us-east-1
jobs:
- name: build-theme-assets
  serial: true
  plan:
  - get: ocw-hugo-themes
    trigger: true
  - task: build-ocw-hugo-themes
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: mitodl/ocw-course-publisher, tag: latest}
      inputs:
      - name: ocw-hugo-themes
      outputs:
      - name: ocw-hugo-themes
      params:
        SEARCH_API_URL: ((search-api-url))
      run:
        path: sh
        args:
        - -exc
        - |
          cd ocw-hugo-themes
          yarn install --pure-lockfile
          npm run build:webpack
          npm run build:githash
  - put: ocw-artifacts
    params:
      source: ocw-hugo-themes/base-theme/dist
      destination:
      - dir: s3-remote:((ocw-bucket-draft))
        command: copy
        args:
        - --ignore-size
        - --checksum
  - put: ocw-artifacts
    params:
      source: ocw-hugo-themes/base-theme/dist
      destination:
      - dir: s3-remote:((ocw-bucket-live))
        command: copy
        args:
        - --ignore-size
        - --checksum
  - put: ocw-artifacts
    params:
      source: ocw-hugo-themes/base-theme/data/webpack.json
      destination:
      - dir: s3-remote:ol-eng-artifacts/ocw-hugo-themes/((hugo-theme-branch))
        command: copy
        args:
        - --ignore-size
        - --checksum
