---
name: Production Deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [release]
  workflow_dispatch: # manual trigger

jobs:
  # runs if CI workflow was successful OR if this was manually triggered
  on-success:
    runs-on: ubuntu-22.04
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      with:
        ref: release
    - uses: akhileshns/heroku-deploy@e86b991436e126ff9d78399b801a6610a64881c9
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "ocw-studio"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: release
  # runs ONLY on a failure of the CI workflow
  on-failure:
    runs-on: ubuntu-22.04
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'failure'
    steps:
    - run: echo 'The triggering workflow failed'
